apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "coral-api.fullname" . }}
  labels:
    {{- include "coral-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "coral-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "coral-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.env }}
          env:
             {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: {{ .Values.service.targetPortName }}
              containerPort: 8000
              protocol: TCP
          volumeMounts:
            - name: artifact-path
              mountPath: {{ .Values.artifact.basePath }}
          livenessProbe:
            httpGet:
              path: /docs
              port: {{ .Values.service.targetPortName }}
          readinessProbe:
            httpGet:
              path: /docs
              port: {{ .Values.service.targetPortName }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: artifact-path
          persistentVolumeClaim:
            claimName: {{ tpl .Values.artifact.name $ }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
