---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ tpl .Values.artifact.name $ }}
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
  selector:
    matchLabels:
      app: {{ template "cafm-api.name" $ }}