version: "3.8"

services:
  cafm-identity-server:
    image: cafm-identity:local
    build:
      context: ../../..
      dockerfile: .pkg/local/docker/Dockerfile
    ports:
      - "9999:9999"
    entrypoint: ["hupper", "python", "-m", "src.port_adapter.api.grpc.server"]
    working_dir: /app
    networks:
      - cafm-infra_default
    volumes:
      - ../../..:/app

  cafm-identity-api-cmd:
    image: cafm-identity:local
    entrypoint: ["hupper", "python", "-m", "src.port_adapter.messaging.listener.api_command.ApiCommandListener"]
    working_dir: /app
    networks:
      - cafm-infra_default
    volumes:
      - ../../..:/app
    depends_on:
      - cafm-identity-server

  cafm-identity-cmd:
    image: cafm-identity:local
    entrypoint: ["hupper", "python", "-m", "src.port_adapter.messaging.listener.identity_command.IdentityCommandListener"]
    working_dir: /app
    networks:
      - cafm-infra_default
    volumes:
      - ../../..:/app
    depends_on:
      - cafm-identity-server

  cafm-identity-project-evt:
    image: cafm-identity:local
    entrypoint: ["hupper", "python", "-m", "src.port_adapter.messaging.listener.project_event.ProjectEventListener"]
    working_dir: /app
    networks:
      - cafm-infra_default
    volumes:
      - ../../..:/app
    depends_on:
      - cafm-identity-server

  cafm-identity-identity-evt:
    image: cafm-identity:local
    entrypoint: ["hupper", "python", "-m", "src.port_adapter.messaging.listener.identity_event.IdentityEventListener"]
    working_dir: /app
    networks:
      - cafm-infra_default
    volumes:
      - ../../..:/app
    depends_on:
      - cafm-identity-server

  cafm-identity-script:
    image: cafm-identity:local
    command: >
      bash -c "python -m src.resource.script.admin_script init-kafka-topics-and-schemas
      && python -m src.resource.script.admin_script init-db
      && python -m src.resource.script.admin_script create-user ${EMAIL:-admin@local.me} ${PASSWORD:-1234} ${DB_NAME:-cafm-identity}
      && python -m src.resource.script.admin_script assign-user-super-admin-role ${USERNAME:-admin@local.me} ${PASSWORD:-1234} ${DB_NAME:-cafm-identity}
      && python -m src.resource.script.admin_script build-resource-tree-from-file ${TREE_FILE:-src/resource/script/__test_tree.yaml.sample}"
    working_dir: /app
    networks:
      - cafm-infra_default
    volumes:
      - ../../..:/app
    depends_on:
      - cafm-identity-server

networks:
  cafm-infra_default:
    external: true
