@startuml "system_c4model"
!include puml/c4_container.puml
!include puml/c4_component.puml

skinparam wrapWidth 200
skinparam maxMessageSize 200

LAYOUT_TOP_DOWN()
'LAYOUT_AS_SKETCH()
LAYOUT_WITH_LEGEND()


Container_Boundary(redis, "Redis System") {
	Component(api__redis, "Api Caching & Response", "tcp", "Has response, caching results")
}
Container_Boundary(api, "Api Microservice") {
	Component(api__identity_permission_py__getPermissions, "Get Permissions", "http(s)", "Get all permissions")
	ComponentQueue(api__identity_realm_py__update__api_command_topic, "update_realm", "api command topic", "")
	Component(api__identity_project_py__create, "Create Project", "http(s)", "")
	ComponentQueue(api__identity_user_group_py__update__api_command_topic, "update_user_group", "api command topic", "")
	ComponentQueue(api__identity_ou_py__create__api_command_topic, "create_ou", "api command topic", "")
	Component(api__identity_realm_py__create, "Create Realm", "http(s)", "")
	Component(api__identity_project_py__getProjects, "Get Projects", "http(s)", "Get all projects")
	Component(api__identity_user_group_py__create, "Create User Group", "http(s)", "")
	ComponentQueue(api__identity_permission_py__create__api_command_topic, "create_permission", "api command topic", "")
	ComponentQueue(api__identity_role_py__update__api_command_topic, "delete_role", "api command topic", "")
	Component(api__identity_user_group_py__update, "Update User Group", "http(s)", "")
	Component(api__identity_realm_py__delete, "Delete Realm", "http(s)", "")
	Component(api__identity_permission_py__delete, "Delete Permission", "http(s)", "")
	Component(api__identity_user_py__create, "Create User", "http(s)", "")
	ComponentQueue(api__identity_project_py__delete__api_command_topic, "delete_project", "api command topic", "")
	Component(api__identity_user_group_py__getUserGroups, "Get User Groups", "http(s)", "get all user groups")
	Component(api__identity_user_group_py__getUserGroup, "Get User Group", "http(s)", "get user group by id")
	Component(api__identity_ou_py__create, "Create Ou", "http(s)", "")
	Component(api__identity_ou_py__delete, "Delete Ou", "http(s)", "")
	Component(api__identity_user_py__resetUserPassword, "Reset User Password", "http(s)", "")
	ComponentQueue(api__identity_user_group_py__delete__api_command_topic, "delete_user_group", "api command topic", "")
	Component(api__auth_py__authenticate, "Authenticate a user", "json/https", "Authenticate a user")
	Component(api__identity_permission_py__create, "Create Permission", "http(s)", "")
	Component(api__identity_user_group_py__delete, "Delete User Group", "http(s)", "")
	Component(api__identity_permission_py__update, "Update Permission", "http(s)", "")
	Component(api__identity_permission_py__getPermission, "Get Permission", "http(s)", "Get permission by id")
	Component(api__identity_user_py__setUserPassword, "Set User Password", "http(s)", "")
	ComponentQueue(api__identity_permission_py__update__api_command_topic, "update_permission", "api command topic", "")
	Component(api__identity_role_py__getRole, "Get Role", "http(s)", "Get role by id")
	Component(api__identity_ou_py__getOu, "Get Ou", "http(s)", "Get ou by id")
	ComponentQueue(api__identity_ou_py__delete__api_command_topic, "delete_ou", "api command topic", "")
	ComponentQueue(api__identity_project_py__create__api_command_topic, "create_project", "api command topic", "")
	Component(api__identity_permission_context_py__delete, "Delete Permission Context", "http(s)", "")
	ComponentQueue(api__identity_permission_context_py__create__api_command_topic, "create_permission_context", "api command topic", "")
	Component(api__identity_ou_py__update, "Update Ou", "http(s)", "")
	Component(api__project_project_py__update, "Update Project", "http(s)", "")
	Component(api__identity_realm_py__getRealms, "Get Realms", "http(s)", "")
	ComponentQueue(api__identity_permission_context_py__delete__api_command_topic, "delete_permission_context", "api command topic", "")
	ComponentQueue(api__identity_user_py__delete__api_command_topic, "delete_user", "api command topic", "")
	Component(api__identity_role_py__create, "Create Role", "http(s)", "")
	ComponentQueue(api__identity_realm_py__create__api_command_topic, "create_realm", "api command topic", "")
	Component(api__identity_permission_context_py__getPermissionContexts, "Get Permission Contexts", "http(s)", "Get all permission contexts")
	ComponentQueue(api__identity_permission_context_py__update__api_command_topic, "update_permission_context", "api command topic", "")
	Component(api__identity_role_py__update, "Update Role", "http(s)", "")
	Component(api__identity_realm_py__getRealm, "Get Realm", "http(s)", "Get realm by id")
	Component(api__identity_ou_py__getOus, "Get Ous", "http(s)", "")
	Component(api__identity_permission_context_py__update, "Update Permission Context", "http(s)", "")
	ComponentQueue(api__identity_ou_py__update__api_command_topic, "update_ou", "api command topic", "")
	Component(api__identity_project_py__delete, "Delete Project", "http(s)", "")
	Component(api__identity_permission_context_py__create, "Create Permission Context", "http(s)", "")
	ComponentQueue(api__identity_user_py__create__api_command_topic, "create_user", "api command topic", "")
	Component(api__identity_realm_py__update, "Update Realm", "http(s)", "")
	Component(api__identity_project_py__getProject, "Get Project", "http(s)", "Get project by id")
	Component(api__identity_role_py__delete, "Delete Role", "http(s)", "")
	ComponentQueue(api__identity_user_py__resetUserPassword__api_command_topic, "reset_user_password", "api command topic", "")
	ComponentQueue(api__identity_role_py__delete__api_command_topic, "delete_role", "api command topic", "")
	Component(api__identity_user_py__getUsers, "Get Users", "http(s)", "Get all users")
	ComponentQueue(api__identity_permission_py__delete__api_command_topic, "delete_permission", "api command topic", "")
	ComponentQueue(api__identity_role_py__create__api_command_topic, "create_role", "api command topic", "")
	ComponentQueue(api__identity_realm_py__delete__api_command_topic, "delete_realm", "api command topic", "")
	Component(api__identity_role_py__getRoles, "Get Roles", "http(s)", "Get all roles")
	Component(api__identity_user_py__getUser, "Get User", "http(s)", "Get user by id")
	Component(api__identity_user_py__delete, "Delete User", http(s)", "")
	ComponentQueue(api__project_project_py__update__api_command_topic, "update_project", "api command topic", "")
	ComponentQueue(api__identity_user_py__setUserPassword__api_command_topic, "set_user_password", "api command topic", "")
	Component(api__identity_permission_context_py__getPermissionContext, "Get Permission Context", "http(s)", "Get permission context by id")
	ComponentQueue(api__identity_user_group_py__create__api_command_topic, "create_user_group", "api command topic", "")
	Component(api__auth_py__logout, "logout", "json/https", "logout a user")
}
Container_Boundary(identity, "Identity Microservice") {
	ComponentQueue(identity__messaging_api_command_handler__UpdatePermissionContextHandler, "update_permission_context", "api command consumer", "")
	ComponentQueue(identity__messaging_api_command_handler__DeletePermissionContextHandler, "delete_permission_context", "api command consumer", "")
	ComponentQueue(identity__domainmodel_event__RealmDeleted, "realm_deleted", "message", "event")
	Component(identity__grpc__AuthAppServiceListener__authenticateUserByEmailAndPassword, "Auth user by email and password", "grpc listener", "Authenticate a user")
	ComponentQueue(identity__domainmodel_event__UserPasswordSet, "user_password_set", "message", "event")
	ComponentQueue(identity__messaging_api_command_handler__DeletePermissionHandler, "delete_permission", "api command consumer", "")
	ComponentQueue(identity__domainmodel_event__ProjectCreated, "project_created", "message", "event")
	ComponentQueue(identity__domainmodel_event__RoleToUserAssignmentRevoked, "role_to_user_assignment_revoked", "message", "event")
	ComponentQueue(identity__messaging_api_command_handler__CreateUserGroupHandler, "create_user_group", "api command consumer", "")
	ComponentQueue(identity__domainmodel_event__UserUpdated, "user_updated", "message", "event")
	ComponentQueue(identity__messaging_api_command_handler__CreateProjectHandler, "create_project", "api command consumer", "")
	ComponentQueue(identity__domainmodel_event__UserWithOneTimePasswordLoggedIn, "user_with_one_time_password_logged_in", "message", "event")
	ComponentQueue(identity__messaging_api_command_handler__UpdateUserGroupHandler, "update_user_group", "api command consumer", "")
	ComponentQueue(identity__messaging_api_command_handler__DeleteOuHandler, "delete_ou", "api command consumer", "")
	ComponentQueue(identity__domainmodel_event__PermissionContextUpdated, "permission_context_updated", "message", "event")
	Component(identity__grpc__CityAppServiceListener__cities, "Get cities", "grpc listener", "Get all cities")
	Component(identity__grpc__CountryAppServiceListener__citiesByCountryId, "Get cities by country id", "grpc listener", "Get cities by country id")
	ComponentQueue(identity__messaging_project_event_handler__UserCreatedHandler, "user_created", "project event consumer", "Generate user one time password")
	Component(identity__grpc__PermissionContextAppServiceListener__permissionContextById, "Get permission context by id", "grpc listener", "Get a permission context by id")
	Component(identity__grpc__PermissionAppServiceListener__permissions, "Get permission", "grpc listener", "Get all permissions")
	ComponentQueue(identity__messaging_api_command_handler__UpdateRoleHandler, "update_role", "api command consumer", "")
	ComponentQueue(identity__messaging_api_command_handler__CreatePermissionContextHandler, "create_permission_context", "api command consumer", "")
	Component(identity__grpc__CountryAppServiceListener__cityByCountryId, "Get city by country id", "grpc listener", "Get a city by country id")
	ComponentQueue(identity__messaging_api_command_handler__UpdateRealmHandler, "update_realm", "api command consumer", "")
	ComponentQueue(identity__messaging_api_command_handler__CreateRealmHandler, "create_realm", "api command consumer", "")
	Component(identity__grpc__AuthAppServiceListener__logout, "Logout user", "grpc listener", "Logout a user")
	Component(identity__grpc__RoleAppServiceListener__roles, "Get roles", "grpc listener", "Get all roles")
	ComponentQueue(identity__domainmodel_event__UserGroupCreated, "user_group_created", "message", "event")
	ComponentQueue(identity__domainmodel_event__RoleToUserAssigned, "role_to_user_assigned", "message", "event")
	ComponentQueue(identity__messaging_api_command_handler__DeleteRealmHandler, "delete_realm", "api command consumer", "")
	ComponentQueue(identity__messaging_identity_event_handler__UserOneTimePasswordGeneratedHandler, "user_one_time_password_generated", "identity event consumer", "")
	ComponentQueue(identity__domainmodel_event__RealmCreated, "realm_created", "message", "event")
	ComponentQueue(identity__messaging_project_event_handler__UserUpdatedHandler, "user_updated", "project event consumer", "")
	Component(identity__grpc__ProjectAppServiceListener__projects, "Get projects", "grpc listener", "Get all projects")
	ComponentQueue(identity__domainmodel_event__PermissionDeleted, "permission_deleted", "message", "event")
	ComponentQueue(identity__domainmodel_event__PermissionContextCreated, "permission_context_created", "message", "event")
	Component(identity__grpc__CityAppServiceListener__cityById, "Get city by id", "grpc listener", "Get a city by id")
	ComponentQueue(identity__domainmodel_event__UserGroupDeleted, "user_group_deleted", "message", "event")
	ComponentQueue(identity__messaging_api_command_handler__CreateOuHandler, "create_ou", "api command consumer", "")
	ComponentQueue(identity__domainmodel_event__ProjectUpdated, "project_updated", "message", "event")
	Component(identity__grpc__CountryAppServiceListener__countries, "Get countries", "grpc listener", "Get all countries")
	ComponentQueue(identity__domainmodel_event__OuUpdated, "ou_updated", "message", "event")
	ComponentQueue(identity__messaging_api_command_handler__ResetUserPasswordHandler, "reset_user_password", "api command consumer", "")
	ComponentQueue(identity__domainmodel_event__OuCreated, "ou_created", "message", "event")
	Component(identity__grpc__RoleAppServiceListener__roleById, "Get role by id", "grpc listener", "Get a role by id")
	Component(identity__grpc__OuAppServiceListener__ouById, "Get ou by id", "grpc listener", "Get a ou by id")
	Component(identity__grpc__CountryAppServiceListener__countryById, "Get country by id", "grpc listener", "Get a country by id")
	ComponentQueue(identity__domainmodel_event__UserOneTimePasswordGenerated, "user_one_time_password_generated", "message", "event")
	ComponentQueue(identity__messaging_api_command_handler__UpdateProjectHandler, "update_project", "api command consumer", "")
	ComponentQueue(identity__messaging_api_command_handler__SetUserPasswordHandler, "set_user_password", "api command consumer", "")
	ComponentQueue(identity__domainmodel_event__RoleDeleted, "role_deleted", "message", "event")
	Component(identity__grpc__OuAppServiceListener__ous, "Get ous", "grpc listener", "Get all ous")
	ComponentQueue(identity__domainmodel_event__UserToRealmAssignmentRevoked, "user_to_realm_assignment_revoked", "message", "event")
	Component(identity__grpc__PermissionContextAppServiceListener__permissionContexts, "Get permission contexts", "grpc listener", "Get all permission contexts")
	ComponentQueue(identity__messaging_api_command_handler__CreateUserHandler, "create_user", "api command consumer", "")
	ComponentQueue(identity__messaging_identity_command_handler__SendEmailOneTimeUserPasswordHandler, "send_email_one_time_user_password", "identity command consumer", "")
	ComponentQueue(identity__messaging_api_command_handler__CreatePermissionHandler, "create_permission", "api command consumer", "")
	ComponentQueue(identity__messaging_api_command_handler__CreateRoleHandler, "create_role", "api command consumer", "")
	Component(identity__grpc__UserAppServiceListener__users, "Get users", "grpc listener", "Get all users")
	ComponentQueue(identity__messaging_api_command_handler__DeleteUserGroupHandler, "delete_user_group", "api command consumer", "")
	ComponentQueue(identity__domainmodel_event__ProjectDeleted, "project_deleted", "message", "event")
	ComponentQueue(identity__messaging_api_command_handler__DeleteProjectHandler, "delete_project", "api command consumer", "")
	ComponentQueue(identity__domainmodel_event__RoleUpdated, "role_updated", "message", "event")
	ComponentQueue(identity__domainmodel_event__RoleCreated, "role_created", "message", "event")
	ComponentQueue(identity__messaging_identity_command_handler__DeleteUserOneTimePasswordHandler, "delete_user_one_time_password", "identity command consumer", "")
	ComponentQueue(identity__domainmodel_event__UserDeleted, "user_created", "message", "event")
	Component(identity__grpc__UserAppServiceListener__userById, "Get user by id", "grpc listener", "Get a user by id")
	ComponentQueue(identity__domainmodel_event__OuDeleted, "ou_deleted", "message", "event")
	Component(identity__grpc__PermissionAppServiceListener__permissionById, "Get permission by id", "grpc listener", "Get a permission by id")
	ComponentQueue(identity__messaging_api_command_handler__UpdatePermissionHandler, "update_permission", "api command consumer", "")
	ComponentQueue(identity__domainmodel_event__UserToRealmAssigned, "user_to_realm_assigned", "message", "event")
	Component(identity__grpc__UserGroupAppServiceListener__userGroups, "Get user groups", "grpc listener", "Get all user groups")
	Component(identity__grpc__ProjectAppServiceListener__projectById, "Get project by id", "grpc listener", "Get a project by id")
	ComponentQueue(identity__domainmodel_event__UserGroupUpdated, "user_group_updated", "message", "event")
	ComponentQueue(identity__domainmodel_event__UserCreated, "user_created", "message", "event")
	ComponentQueue(identity__messaging_api_command_handler__DeleteUserHandler, "delete_user", "api command consumer", "")
	Component(identity__grpc__RealmAppServiceListener__realmById, "Get realm by id", "grpc listener", "Get a realm by id")
	ComponentQueue(identity__domainmodel_event__RealmUpdated, "realm_updated", "message", "event")
	ComponentQueue(identity__domainmodel_event__PermissionContextDeleted, "permission_context_deleted", "message", "event")
	ComponentQueue(identity__messaging_api_command_handler__UpdateOuHandler, "update_ou", "api command consumer", "")
	ComponentQueue(identity__messaging_api_command_handler__DeleteRoleHandler, "delete_role", "api command consumer", "")
	Component(identity__grpc__UserGroupAppServiceListener__userGroupById, "Get user group by id", "grpc listener", "Get a user group by id")
	ComponentQueue(identity__domainmodel_event__PermissionUpdated, "permission_updated", "message", "event")
	Component(identity__grpc__RealmAppServiceListener__realms, "Get realms", "grpc listener", "Get all realms")
	ComponentQueue(identity__domainmodel_event__PermissionCreated, "permission_created", "message", "event")
	ComponentQueue(identity__messaging_identity_event_handler__UserWithOneTimePasswordLoggedInHandler, "user_with_one_time_password_logged_in", "identity event consumer", "")
}
Container_Boundary(project, "Project Microservice") {
	ComponentQueue(project__domainmodel_event__OrganizationCreated, "Organization Created", "event", "message")
	ComponentQueue(project__messaging_identity_event_handler__UserUpdatedHandler, "user_updated", "identity event consumer", "User updated")
	ComponentQueue(project__domainmodel_event__RoleCreated, "Role Created", "event", "message")
	Component(identity__grpc__UserLookupAppServiceListener__userLookupByUserId, "Get a user lookup by id", "grpc listener", "Get a user lookup by id")
	ComponentQueue(project__domainmodel_event__UserUpdated, "User Updated", "event", "message")
	ComponentQueue(project__messaging_project_command_handler__DeleteOrganizationHandler, "delete_organization", "project command consumer", "")
	ComponentQueue(project__messaging_project_command_handler__CreateUserHandler, "create_user", "project command consumer", "Create User")
	ComponentQueue(project__domainmodel_event__ProjectCreated, "Project Created", "event", "message")
	ComponentQueue(project__messaging_project_command_handler__CreateRoleHandler, "create_role", "project command consumer", "")
	Component(identity__grpc__ProjectAppServiceListener__projectById, "Get project by id", "grpc listener", "Get a project by id")
	ComponentQueue(project__messaging_identity_event_handler__RoleCreatedHandler, "role_created", "identity event consumer", "")
	ComponentQueue(project__domainmodel_event__UserDeleted, "User Deleted", "event", "message")
	ComponentQueue(project__messaging_project_command_handler__UpdateOrganizationHandler, "update_organization", "project command consumer", "")
	Component(identity__grpc__UserAppServiceListener__users, "Get all users", "grpc listener", "Get users")
	ComponentQueue(project__domainmodel_event__RoleUpdated, "Role Updated", "event", "message")
	ComponentQueue(project__domainmodel_event__ProjectUpdated, "Project Updated", "event", "message")
	ComponentQueue(project__messaging_project_command_handler__UpdateOrganizationHandler, "Update Organization", "project command consumer", "Update Organization")
	ComponentQueue(project__messaging_identity_event_handler__ProjectDeletedHandler, "project_deleted", "identity event consumer", "Project deleted")
	ComponentQueue(project__domainmodel_event__UserCreated, "User Created", "event", "message")
	ComponentQueue(project__domainmodel_event__RoleToUserAssignmentRevoked, "Role to User Assignment Revoked", "event", "message")
	Component(identity__grpc__OrganizationAppServiceListener__organizations, "Get organizations", "grpc listener", "Get all organizations")
	ComponentQueue(project__messaging_identity_event_handler__ProjectCreatedHandler, "project_created", "identity event consumer", "")
	ComponentQueue(project__messaging_identity_event_handler__RoleToUserAssignmentRevokedHandler, "role_to_user_assignment_revoked", "identity event consumer", "")
	ComponentQueue(project__messaging_identity_event_handler__RoleToUserAssignedHandler, "role_to_user_assigned", "identity event consumer", "")
	ComponentQueue(project__messaging_project_command_handler__UpdateUserHandler, "update_user", "project command consumer", "")
	Component(identity__grpc__UserLookupAppServiceListener__userLookups, "Get a user lookups", "grpc listener", "Get user lookups")
	ComponentQueue(project__messaging_identity_event_handler__UserDeletedHandler, "user_deleted", "identity event consumer", "")
	ComponentQueue(project__domainmodel_event__UserToOrganizationAssigned, "User to Organization Assigned", "event", "message")
	ComponentQueue(project__messaging_identity_event_handler__RealmCreatedHandler, "realm_created", "identity event consumer", "")
	Component(identity__grpc__ProjectAppServiceListener__projects, "Get projects", "grpc listener", "Get all projects")
	Component(identity__grpc__UserAppServiceListener__userById, "Get a user by id", "grpc listener", "Get a user by id")
	ComponentQueue(project__messaging_project_command_handler__DeleteOrganizationHandler, "Delete Organization", "project command consumer", "Delete Organization")
	ComponentQueue(project__messaging_identity_event_handler__UserToRealmAssignedHandler, "user_to_realm_assigned", "identity event consumer", "")
	ComponentQueue(project__domainmodel_event__ProjectStateChanged, "Project State Changed", "event", "message")
	ComponentQueue(project__domainmodel_event__RoleDeleted, "Role Deleted", "event", "message")
	Component(identity__grpc__ProjectAppServiceListener__projectByName, "Get project by name", "grpc listener", "Get a project by name")
	ComponentQueue(project__domainmodel_event__OrganizationUpdated, "Organization Updated", "event", "message")
	ComponentQueue(project__domainmodel_event__OrganizationDeleted, "Organization Deleted", "event", "message")
	ComponentQueue(project__messaging_project_command_handler__RevokeRoleToUserAssignmentHandler, "revoke_role_to_user_assignment", "project command consumer", "Revoke Role to User Assignment")
	ComponentQueue(project__messaging_project_command_handler__AssignUserToOrganizationHandler, "assign_user_to_organization", "project command consumer", "")
	Component(identity__grpc__UserLookupAppServiceListener__userLookupByUserEmail, "Get a user lookup by email", "grpc listener", "Get a user lookup by email")
	ComponentQueue(project__messaging_project_command_handler__RevokeUserToOrganizationAssignmentHandler, "revoke_user_to_organization_assignment", "project command consumer", "")
	ComponentQueue(project__domainmodel_event__ProjectDeleted, "Project Created", "event", "message")
	ComponentQueue(project__messaging_project_command_handler__DeleteUserHandler, "delete_user", "project command consumer", "")
	ComponentQueue(project__messaging_project_command_handler__AssignRoleToUserHandler, "assign_role_to_user", "project command consumer", "")
	ComponentQueue(project__messaging_project_command_handler__CreateOrganizationHandler, "create_organization", "project command consumer", "")
	ComponentQueue(project__messaging_identity_event_handler__UserToRealmAssignmentRevokedHandler, "user_to_realm_assignment_revoked", "identity event consumer", "")
	ComponentQueue(project__domainmodel_event__RoleToUserAssigned, "Role to User Assigned", "event", "message")
	Component(identity__grpc__UserAppServiceListener__userByEmail, "Get a user by email", "grpc listener", "Get a user by email")
	ComponentQueue(project__messaging_project_command_handler__DeleteProjectHandler, "delete_project", "project command consumer", "")
	ComponentQueue(project__domainmodel_event__UserToOrganizationAssignmentRevoked, "User to Organization Assignment Revoked", "event", "message")
	ComponentQueue(project__messaging_identity_event_handler__UserCreatedHandler, "user_created", "identity event consumer", "")
	Component(identity__grpc__OrganizationAppServiceListener__organizationById, "Get organization by id", "grpc listener", "Get a organization by id")
	ComponentQueue(project__messaging_project_command_handler__CreateProjectHandler, "create_project", "project command consumer", "")
}
Rel(api__identity_permission_context_py__getPermissionContexts, identity__grpc__PermissionContextAppServiceListener__permissionContexts, "Get permission contexts", "grpc")
Rel(identity__messaging_api_command_handler__CreateOuHandler, identity__domainmodel_event__OuCreated, "create")
Rel(api__identity_permission_py__create__api_command_topic, identity__messaging_api_command_handler__CreatePermissionHandler, "create_permission", "message")
Rel(project__messaging_project_command_handler__AssignUserToOrganizationHandler, project__domainmodel_event__UserToOrganizationAssigned, "create")
Rel(identity__messaging_api_command_handler__DeleteRoleHandler, identity__domainmodel_event__RoleDeleted, "create")
Rel(api__identity_ou_py__create__api_command_topic, identity__messaging_api_command_handler__CreateOuHandler, "create_ou", "message")
Rel(project__messaging_identity_event_handler__RoleToUserAssignedHandler, project__messaging_project_command_handler__AssignRoleToUserHandler, "assign_role_to_user", "message")
Rel(identity__messaging_api_command_handler__DeleteProjectHandler, identity__domainmodel_event__ProjectDeleted, "create")
Rel(api__identity_permission_py__getPermission, identity__grpc__PermissionAppServiceListener__permissionById, "Get permission by id", "grpc")
Rel(project__messaging_project_command_handler__CreateRoleHandler, project__domainmodel_event__RoleCreated, "create")
Rel(api__identity_role_py__create, api__identity_role_py__create__api_command_topic, "create_role", "message")
Rel(api__identity_permission_py__update__api_command_topic, identity__messaging_api_command_handler__UpdatePermissionHandler, "update_permission", "message")
Rel(identity__messaging_project_event_handler__UserCreatedHandler, identity__domainmodel_event__UserOneTimePasswordGenerated, "create")
Rel(api__identity_permission_context_py__create, api__identity_permission_context_py__create__api_command_topic, "create_permission_context", "message")
Rel(identity__messaging_api_command_handler__CreatePermissionHandler, identity__domainmodel_event__PermissionCreated, "create")
Rel(identity__messaging_api_command_handler__UpdateOuHandler, identity__domainmodel_event__OuUpdated, "create")
Rel(api__auth_py__authenticate, identity__grpc__AuthAppServiceListener__authenticateUserByEmailAndPassword, "Auth user & get token", "grpc call")
Rel(api__project_project_py__update, api__project_project_py__update__api_command_topic, "update_project", "message")
Rel(api__identity_permission_py__update, api__identity_permission_py__update__api_command_topic, "update_permission", "message")
Rel(api__identity_realm_py__getRealms, identity__grpc__RealmAppServiceListener__realms, "Get realms", "grpc")
Rel(api__identity_user_group_py__delete__api_command_topic, identity__messaging_api_command_handler__DeleteUserGroupHandler, "delete_user_group", "message")
Rel(project__messaging_identity_event_handler__ProjectDeletedHandler, identity__domainmodel_event__ProjectDeleted, "consume")
Rel(identity__messaging_api_command_handler__SetUserPasswordHandler, identity__messaging_api_command_handler__SetUserPasswordHandler, "set_user_password", "message")
Rel(project__messaging_identity_event_handler__UserToRealmAssignmentRevokedHandler, identity__domainmodel_event__UserToRealmAssignmentRevoked, "consume")
Rel(api__identity_project_py__create__api_command_topic, identity__messaging_api_command_handler__CreateProjectHandler, "create_project", "message")
Rel(project__messaging_identity_event_handler__RoleCreatedHandler, identity__domainmodel_event__RoleCreated, "consume")
Rel(api__identity_realm_py__delete__api_command_topic, identity__messaging_api_command_handler__DeleteRealmHandler, "delete_realm", "message")
Rel(identity__messaging_api_command_handler__DeleteUserGroupHandler, identity__domainmodel_event__UserGroupDeleted, "create")
Rel(project__messaging_project_command_handler__DeleteOrganizationHandler, project__domainmodel_event__OrganizationDeleted, "Organization Deleted", "message")
Rel(api__identity_ou_py__update, api__identity_ou_py__update__api_command_topic, "update_ou", "message")
Rel(identity__messaging_api_command_handler__DeletePermissionContextHandler, identity__domainmodel_event__PermissionContextDeleted, "create")
Rel(api__identity_user_group_py__update__api_command_topic, identity__messaging_api_command_handler__UpdateUserGroupHandler, "update_user_group", "message")
Rel(project__messaging_project_command_handler__AssignRoleToUserHandler, project__domainmodel_event__RoleToUserAssigned, "create")
Rel(identity__messaging_api_command_handler__CreatePermissionContextHandler, identity__domainmodel_event__PermissionContextCreated, "create")
Rel(api__identity_ou_py__getOu, identity__grpc__OuAppServiceListener__ouById, "Get ou by id", "grpc")
Rel(project__messaging_identity_event_handler__UserToRealmAssignedHandler, project__messaging_project_command_handler__AssignUserToOrganizationHandler, "assign_user_to_organization", "message")
Rel(api__identity_permission_context_py__create__api_command_topic, identity__messaging_api_command_handler__CreatePermissionContextHandler, "create_permission_context", "message")
Rel(api__identity_role_py__delete, api__identity_role_py__delete__api_command_topic, "delete_role", "message")
Rel(api__project_project_py__update__api_command_topic, identity__messaging_api_command_handler__UpdateProjectHandler, "update_project", "message")
Rel(api__identity_role_py__update, api__identity_role_py__update__api_command_topic, "delete_role", "message")
Rel(project__messaging_identity_event_handler__UserToRealmAssignmentRevokedHandler, project__messaging_project_command_handler__RevokeUserToOrganizationAssignmentHandler, "revoke_user_to_organization_assignment", "message")
Rel(identity__messaging_api_command_handler__CreateRealmHandler, identity__domainmodel_event__RealmCreated, "create")
Rel(project__messaging_project_command_handler__UpdateUserHandler, project__domainmodel_event__UserUpdated, "create")
Rel(identity__messaging_api_command_handler__DeleteOuHandler, identity__domainmodel_event__OuDeleted, "create")
Rel(api__identity_permission_context_py__update, api__identity_permission_context_py__update__api_command_topic, "update_permission_context", "message")
Rel(identity__messaging_project_event_handler__UserUpdatedHandler, project__domainmodel_event__UserUpdated, "consume")
Rel(project__messaging_identity_event_handler__UserCreatedHandler, project__messaging_project_command_handler__CreateUserHandler, "create_user", "message")
Rel(identity__messaging_api_command_handler__ResetUserPasswordHandler, identity__domainmodel_event__UserOneTimePasswordGenerated, "create")
Rel(api__identity_user_group_py__getUserGroup, identity__grpc__UserGroupAppServiceListener__userGroupById, "Get user group by id", "grpc")
Rel(api__identity_realm_py__update, api__identity_realm_py__update__api_command_topic, "update_realm", "message")
Rel(identity__messaging_api_command_handler__DeleteUserGroupHandler, identity__domainmodel_event__UserGroupUpdated, "create")
Rel(api__identity_user_py__create, api__identity_user_py__create__api_command_topic, "create_user", "message")
Rel(identity__messaging_api_command_handler__CreateRoleHandler, identity__domainmodel_event__RoleCreated, "create")
Rel(project__messaging_identity_event_handler__RoleCreatedHandler, project__messaging_project_command_handler__CreateRoleHandler, "create_role", "message")
Rel(identity__messaging_project_event_handler__UserCreatedHandler, project__domainmodel_event__UserCreated, "consume")
Rel(project__messaging_project_command_handler__DeleteUserHandler, project__domainmodel_event__UserDeleted, "create")
Rel(identity__messaging_api_command_handler__UpdateProjectHandler, identity__domainmodel_event__ProjectUpdated, "create")
Rel(api__identity_role_py__getRole, identity__grpc__RoleAppServiceListener__roleById, "Get role by id", "grpc")
Rel(api__identity_permission_context_py__update__api_command_topic, identity__messaging_api_command_handler__UpdatePermissionContextHandler, "update_permission_context", "message")
Rel(identity__messaging_api_command_handler__UpdateRoleHandler, identity__domainmodel_event__RoleUpdated, "create")
Rel(identity__messaging_api_command_handler__DeleteRealmHandler, identity__domainmodel_event__RealmDeleted, "create")
Rel(api__identity_permission_context_py__getPermissionContext, identity__grpc__PermissionContextAppServiceListener__permissionContextById, "Get permission context by id", "grpc")
Rel(api__identity_ou_py__update__api_command_topic, identity__messaging_api_command_handler__UpdateOuHandler, "update_ou", "message")
Rel(api__identity_realm_py__create__api_command_topic, identity__messaging_api_command_handler__CreateRealmHandler, "create_realm", "message")
Rel(api__identity_user_py__resetUserPassword, api__identity_user_py__resetUserPassword__api_command_topic, "reset_user_password", "message")
Rel(project__messaging_project_command_handler__CreateOrganizationHandler, project__domainmodel_event__OrganizationCreated, "create")
Rel(api__identity_realm_py__create, api__identity_realm_py__create__api_command_topic, "create_realm", "message")
Rel(api__identity_project_py__delete, api__identity_project_py__delete__api_command_topic, "delete_project", "message")
Rel(api__identity_ou_py__create, api__identity_ou_py__create__api_command_topic, "create_ou", "message")
Rel(api__identity_user_py__setUserPassword__api_command_topic, identity__messaging_api_command_handler__ResetUserPasswordHandler, "reset_user_password", "message")
Rel(api__identity_role_py__getRoles, identity__grpc__RoleAppServiceListener__roles, "Get roles", "grpc")
Rel(identity__messaging_identity_event_handler__UserWithOneTimePasswordLoggedInHandler, identity__messaging_identity_command_handler__DeleteUserOneTimePasswordHandler, "delete_user_one_time_password", "message")
Rel(identity__messaging_api_command_handler__CreateUserGroupHandler, identity__domainmodel_event__UserGroupCreated, "create")
Rel(api__identity_ou_py__getOus, identity__grpc__OuAppServiceListener__ous, "Get ous", "grpc")
Rel(identity__messaging_api_command_handler__UpdatePermissionHandler, identity__domainmodel_event__PermissionUpdated, "create")
Rel(api__identity_user_py__delete, api__identity_user_py__delete__api_command_topic, "delete_user", "message")
Rel(project__messaging_identity_event_handler__UserToRealmAssignedHandler, identity__domainmodel_event__UserToRealmAssigned, "consume")
Rel(project__messaging_project_command_handler__DeleteOrganizationHandler, project__domainmodel_event__OrganizationDeleted, "create")
Rel(api__identity_user_py__getUsers, identity__grpc__UserAppServiceListener__users, "Get users", "grpc")
Rel(identity__messaging_api_command_handler__DeletePermissionHandler, identity__domainmodel_event__PermissionDeleted, "create")
Rel(project__messaging_project_command_handler__RevokeUserToOrganizationAssignmentHandler, project__domainmodel_event__UserToOrganizationAssignmentRevoked, "create")
Rel(api__identity_permission_context_py__delete__api_command_topic, identity__messaging_api_command_handler__DeletePermissionContextHandler, "delete_permission_context", "message")
Rel(identity__messaging_api_command_handler__UpdateRealmHandler, identity__domainmodel_event__RealmUpdated, "create")
Rel(identity__messaging_api_command_handler__UpdatePermissionContextHandler, identity__domainmodel_event__PermissionContextUpdated, "create")
Rel(project__messaging_project_command_handler__RevokeRoleToUserAssignmentHandler, project__domainmodel_event__RoleToUserAssignmentRevoked, "create")
Rel(api__identity_ou_py__delete, api__identity_ou_py__delete__api_command_topic, "delete_ou", "message")
Rel(project__messaging_identity_event_handler__ProjectCreatedHandler, project__messaging_project_command_handler__CreateProjectHandler, "create_project", "message")
Rel(project__messaging_identity_event_handler__RoleToUserAssignedHandler, identity__domainmodel_event__RoleToUserAssigned, "consume")
Rel(api__identity_permission_py__getPermissions, identity__grpc__PermissionAppServiceListener__permissions, "Get permissions", "grpc")
Rel(api__identity_permission_py__delete__api_command_topic, identity__messaging_api_command_handler__DeletePermissionHandler, "delete_permission", "message")
Rel(api__identity_user_py__getUser, identity__grpc__UserAppServiceListener__userById, "Get user by id", "grpc")
Rel(api__identity_role_py__create__api_command_topic, identity__messaging_api_command_handler__CreateRoleHandler, "create_role", "message")
Rel(api__identity_user_py__resetUserPassword__api_command_topic, identity__messaging_api_command_handler__ResetUserPasswordHandler, "reset_user_password", "message")
Rel(api__identity_project_py__delete__api_command_topic, identity__messaging_api_command_handler__DeleteProjectHandler, "delete_project", "message")
Rel(api__identity_realm_py__update__api_command_topic, identity__messaging_api_command_handler__UpdateRealmHandler, "update_realm", "message")
Rel(identity__messaging_project_event_handler__UserUpdatedHandler, identity__domainmodel_event__UserUpdated, "create")
Rel(project__messaging_project_command_handler__UpdateOrganizationHandler, project__domainmodel_event__OrganizationUpdated, "create")
Rel(project__messaging_identity_event_handler__RealmCreatedHandler, identity__domainmodel_event__RealmCreated, "consume")
Rel(api__identity_permission_py__delete, api__identity_permission_py__delete__api_command_topic, "delete_permission", "message")
Rel(project__messaging_identity_event_handler__UserUpdatedHandler, identity__domainmodel_event__UserUpdated, "consume")
Rel(project__messaging_identity_event_handler__RoleToUserAssignmentRevokedHandler, identity__domainmodel_event__RoleToUserAssignmentRevoked, "consume")
Rel(api__identity_realm_py__getRealm, identity__grpc__RealmAppServiceListener__realmById, "Get realm by id", "grpc")
Rel(api__identity_user_group_py__update, api__identity_user_group_py__update__api_command_topic, "update_user_group", "message")
Rel(project__messaging_identity_event_handler__UserUpdatedHandler, project__messaging_project_command_handler__UpdateUserHandler, "update_user", "message")
Rel(project__messaging_identity_event_handler__RoleToUserAssignmentRevokedHandler, project__messaging_project_command_handler__RevokeRoleToUserAssignmentHandler, "revoke_role_to_user_assignment", "message")
Rel(api__identity_user_group_py__create, api__identity_user_group_py__create__api_command_topic, "create_user_group", "message")
Rel(api__identity_user_py__setUserPassword, api__identity_user_py__setUserPassword__api_command_topic, "set_user_password", "message")
Rel(project__messaging_identity_event_handler__ProjectCreatedHandler, identity__domainmodel_event__ProjectCreated, "consume")
Rel(api__identity_project_py__getProject, identity__grpc__ProjectAppServiceListener__projectById, "Get a project by id", "grpc")
Rel(api__identity_permission_context_py__delete, api__identity_permission_context_py__delete__api_command_topic, "delete_permission_context", "message")
Rel(api__identity_role_py__update__api_command_topic, identity__messaging_api_command_handler__UpdateRoleHandler, "update_role", "message")
Rel(api__identity_role_py__delete__api_command_topic, identity__messaging_api_command_handler__DeleteRoleHandler, "delete_role", "message")
Rel(identity__messaging_api_command_handler__CreateProjectHandler, identity__domainmodel_event__ProjectCreated, "create")
Rel(api__identity_user_group_py__create__api_command_topic, identity__messaging_api_command_handler__CreateUserGroupHandler, "create_user_group", "message")
Rel(api__identity_ou_py__delete__api_command_topic, identity__messaging_api_command_handler__DeleteOuHandler, "delete_ou", "message")
Rel(api__identity_user_py__create__api_command_topic, identity__messaging_api_command_handler__CreateUserHandler, "create_user", "message")
Rel(api__identity_user_group_py__delete, api__identity_user_group_py__delete__api_command_topic, "delete_user_group", "message")
Rel(project__messaging_project_command_handler__DeleteProjectHandler, project__domainmodel_event__ProjectDeleted, "create")
Rel(identity__messaging_api_command_handler__DeleteUserHandler, identity__domainmodel_event__UserDeleted, "create")
Rel(project__messaging_identity_event_handler__UserDeletedHandler, project__messaging_project_command_handler__DeleteUserHandler, "delete_user", "message")
Rel(api__identity_realm_py__delete, api__identity_realm_py__delete__api_command_topic, "delete_realm", "message")
Rel(project__messaging_project_command_handler__CreateProjectHandler, project__domainmodel_event__ProjectCreated, "create", "message")
Rel(project__messaging_identity_event_handler__UserCreatedHandler, identity__domainmodel_event__UserCreated, "consume")
Rel(project__messaging_identity_event_handler__UserDeletedHandler, identity__domainmodel_event__UserDeleted, "consume")
Rel(project__messaging_identity_event_handler__ProjectDeletedHandler, project__messaging_project_command_handler__DeleteProjectHandler, "delete_project", "message")
Rel(project__messaging_project_command_handler__UpdateOrganizationHandler, project__domainmodel_event__OrganizationUpdated, "Organization Updated", "message")
Rel(project__messaging_identity_event_handler__RealmCreatedHandler, project__messaging_project_command_handler__CreateOrganizationHandler, "create_organization", "message")
Rel(api__identity_user_py__delete__api_command_topic, identity__messaging_api_command_handler__DeleteUserHandler, "delete_user", "message")
Rel(api__auth_py__logout, identity__grpc__AuthAppServiceListener__logout, "Logout user by token", "grpc call")
Rel(api__identity_project_py__create, api__identity_project_py__create__api_command_topic, "create_project", "message")
Rel(api__identity_user_group_py__getUserGroups, identity__grpc__UserGroupAppServiceListener__userGroups, "Get user groups", "grpc")
Rel(identity__messaging_api_command_handler__CreateUserHandler, identity__domainmodel_event__UserCreated, "create")
Rel(project__messaging_project_command_handler__CreateUserHandler, project__domainmodel_event__UserCreated, "create")
Rel(api__identity_permission_py__create, api__identity_permission_py__create__api_command_topic, "create_permission", "message")
Rel(identity__messaging_project_event_handler__UserCreatedHandler, identity__domainmodel_event__UserOneTimePasswordGenerated, "consume")
Rel(identity__messaging_identity_event_handler__UserOneTimePasswordGeneratedHandler, identity__messaging_identity_command_handler__SendEmailOneTimeUserPasswordHandler, "send_email_one_time_user_password", "message")
Rel(identity__messaging_identity_event_handler__UserWithOneTimePasswordLoggedInHandler, identity__domainmodel_event__UserWithOneTimePasswordLoggedIn, "consume")
Rel(api__identity_project_py__getProjects, identity__grpc__ProjectAppServiceListener__projects, "Get projects", "grpc")
Rel(api, redis, "Get/Create api response & caching data")

@enduml
