---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "cafm-api.name" $ }}
  labels:
    app: {{ template "cafm-api.name" $ }}
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  mountOptions:
    - nfsvers=3
    - nolock
  nfs:
    path: {{ .Values.nfs.path }}
    server: {{ .Values.nfs.server }}