# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: access_node.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import resource_pb2 as resource__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='access_node.proto',
  package='cafm.identity.access_node',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x61\x63\x63\x65ss_node.proto\x12\x19\x63\x61\x66m.identity.access_node\x1a\x0eresource.proto\"\x87\x01\n\nAccessNode\x12\x32\n\x08resource\x18\x01 \x01(\x0b\x32 .cafm.identity.resource.Resource\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x37\n\x08\x63hildren\x18\x03 \x03(\x0b\x32%.cafm.identity.access_node.AccessNodeb\x06proto3'
  ,
  dependencies=[resource__pb2.DESCRIPTOR,])




_ACCESSNODE = _descriptor.Descriptor(
  name='AccessNode',
  full_name='cafm.identity.access_node.AccessNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='resource', full_name='cafm.identity.access_node.AccessNode.resource', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='cafm.identity.access_node.AccessNode.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='children', full_name='cafm.identity.access_node.AccessNode.children', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=200,
)

_ACCESSNODE.fields_by_name['resource'].message_type = resource__pb2._RESOURCE
_ACCESSNODE.fields_by_name['children'].message_type = _ACCESSNODE
DESCRIPTOR.message_types_by_name['AccessNode'] = _ACCESSNODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AccessNode = _reflection.GeneratedProtocolMessageType('AccessNode', (_message.Message,), {
  'DESCRIPTOR' : _ACCESSNODE,
  '__module__' : 'access_node_pb2'
  # @@protoc_insertion_point(class_scope:cafm.identity.access_node.AccessNode)
  })
_sym_db.RegisterMessage(AccessNode)


# @@protoc_insertion_point(module_scope)
