# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth_app_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='auth_app_service.proto',
  package='coral.identity.auth',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16\x61uth_app_service.proto\x12\x13\x63oral.identity.auth\"Y\n7AuthAppService_authenticateUserByNameAndPasswordRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"I\n8AuthAppService_authenticateUserByNameAndPasswordResponse\x12\r\n\x05token\x18\x01 \x01(\t2\xd5\x01\n\x0e\x41uthAppService\x12\xc2\x01\n!authenticateUserByNameAndPassword\x12L.coral.identity.auth.AuthAppService_authenticateUserByNameAndPasswordRequest\x1aM.coral.identity.auth.AuthAppService_authenticateUserByNameAndPasswordResponse\"\x00\x62\x06proto3'
)




_AUTHAPPSERVICE_AUTHENTICATEUSERBYNAMEANDPASSWORDREQUEST = _descriptor.Descriptor(
  name='AuthAppService_authenticateUserByNameAndPasswordRequest',
  full_name='coral.identity.auth.AuthAppService_authenticateUserByNameAndPasswordRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='coral.identity.auth.AuthAppService_authenticateUserByNameAndPasswordRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='coral.identity.auth.AuthAppService_authenticateUserByNameAndPasswordRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=136,
)


_AUTHAPPSERVICE_AUTHENTICATEUSERBYNAMEANDPASSWORDRESPONSE = _descriptor.Descriptor(
  name='AuthAppService_authenticateUserByNameAndPasswordResponse',
  full_name='coral.identity.auth.AuthAppService_authenticateUserByNameAndPasswordResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='coral.identity.auth.AuthAppService_authenticateUserByNameAndPasswordResponse.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=211,
)

DESCRIPTOR.message_types_by_name['AuthAppService_authenticateUserByNameAndPasswordRequest'] = _AUTHAPPSERVICE_AUTHENTICATEUSERBYNAMEANDPASSWORDREQUEST
DESCRIPTOR.message_types_by_name['AuthAppService_authenticateUserByNameAndPasswordResponse'] = _AUTHAPPSERVICE_AUTHENTICATEUSERBYNAMEANDPASSWORDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AuthAppService_authenticateUserByNameAndPasswordRequest = _reflection.GeneratedProtocolMessageType('AuthAppService_authenticateUserByNameAndPasswordRequest', (_message.Message,), {
  'DESCRIPTOR' : _AUTHAPPSERVICE_AUTHENTICATEUSERBYNAMEANDPASSWORDREQUEST,
  '__module__' : 'auth_app_service_pb2'
  # @@protoc_insertion_point(class_scope:coral.identity.auth.AuthAppService_authenticateUserByNameAndPasswordRequest)
  })
_sym_db.RegisterMessage(AuthAppService_authenticateUserByNameAndPasswordRequest)

AuthAppService_authenticateUserByNameAndPasswordResponse = _reflection.GeneratedProtocolMessageType('AuthAppService_authenticateUserByNameAndPasswordResponse', (_message.Message,), {
  'DESCRIPTOR' : _AUTHAPPSERVICE_AUTHENTICATEUSERBYNAMEANDPASSWORDRESPONSE,
  '__module__' : 'auth_app_service_pb2'
  # @@protoc_insertion_point(class_scope:coral.identity.auth.AuthAppService_authenticateUserByNameAndPasswordResponse)
  })
_sym_db.RegisterMessage(AuthAppService_authenticateUserByNameAndPasswordResponse)



_AUTHAPPSERVICE = _descriptor.ServiceDescriptor(
  name='AuthAppService',
  full_name='coral.identity.auth.AuthAppService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=214,
  serialized_end=427,
  methods=[
  _descriptor.MethodDescriptor(
    name='authenticateUserByNameAndPassword',
    full_name='coral.identity.auth.AuthAppService.authenticateUserByNameAndPassword',
    index=0,
    containing_service=None,
    input_type=_AUTHAPPSERVICE_AUTHENTICATEUSERBYNAMEANDPASSWORDREQUEST,
    output_type=_AUTHAPPSERVICE_AUTHENTICATEUSERBYNAMEANDPASSWORDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_AUTHAPPSERVICE)

DESCRIPTOR.services_by_name['AuthAppService'] = _AUTHAPPSERVICE

# @@protoc_insertion_point(module_scope)
