# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cafm_identity.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import access_node_pb2 as access__node__pb2
import permission_with_permission_contexts_pb2 as permission__with__permission__contexts__pb2
import role_access_permission_pb2 as role__access__permission__pb2
import ou_app_service_pb2 as ou__app__service__pb2
import permission_app_service_pb2 as permission__app__service__pb2
import project_app_service_pb2 as project__app__service__pb2
import realm_app_service_pb2 as realm__app__service__pb2
import permission_context_app_service_pb2 as permission__context__app__service__pb2
import role_app_service_pb2 as role__app__service__pb2
import user_app_service_pb2 as user__app__service__pb2
import user_group_app_service_pb2 as user__group__app__service__pb2
import auth_app_service_pb2 as auth__app__service__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cafm_identity.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x63\x61\x66m_identity.proto\x1a\x11\x61\x63\x63\x65ss_node.proto\x1a)permission_with_permission_contexts.proto\x1a\x1crole_access_permission.proto\x1a\x14ou_app_service.proto\x1a\x1cpermission_app_service.proto\x1a\x19project_app_service.proto\x1a\x17realm_app_service.proto\x1a$permission_context_app_service.proto\x1a\x16role_app_service.proto\x1a\x16user_app_service.proto\x1a\x1cuser_group_app_service.proto\x1a\x16\x61uth_app_service.protob\x06proto3'
  ,
  dependencies=[access__node__pb2.DESCRIPTOR,permission__with__permission__contexts__pb2.DESCRIPTOR,role__access__permission__pb2.DESCRIPTOR,ou__app__service__pb2.DESCRIPTOR,permission__app__service__pb2.DESCRIPTOR,project__app__service__pb2.DESCRIPTOR,realm__app__service__pb2.DESCRIPTOR,permission__context__app__service__pb2.DESCRIPTOR,role__app__service__pb2.DESCRIPTOR,user__app__service__pb2.DESCRIPTOR,user__group__app__service__pb2.DESCRIPTOR,auth__app__service__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
