# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cafm_project.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from project import project_app_service_pb2 as project_dot_project__app__service__pb2
from project import user_app_service_pb2 as project_dot_user__app__service__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
    name="cafm_project.proto",
    package="",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b"\n\x12\x63\x61\x66m_project.proto\x1a!project/project_app_service.proto\x1a\x1eproject/user_app_service.protob\x06proto3",
    dependencies=[
        project_dot_project__app__service__pb2.DESCRIPTOR,
        project_dot_user__app__service__pb2.DESCRIPTOR,
    ],
)


_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
