# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='identity.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eidentity.proto\"U\n/UserAppService_userByUsernameAndPasswordRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"b\n0UserAppService_userByUsernameAndPasswordResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"0\n RoleAppService_roleByNameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"=\n!RoleAppService_roleByNameResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"<\n,PermissionAppService_permissionByNameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"I\n-PermissionAppService_permissionByNameResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\",\n\x1cOuAppService_ouByNameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"9\n\x1dOuAppService_ouByNameResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"2\n\"RealmAppService_realmByNameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"?\n#RealmAppService_realmByNameResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t2\x95\x01\n\x0eUserAppService\x12\x82\x01\n\x19userByUsernameAndPassword\x12\x30.UserAppService_userByUsernameAndPasswordRequest\x1a\x31.UserAppService_userByUsernameAndPasswordResponse\"\x00\x32g\n\x0eRoleAppService\x12U\n\nroleByName\x12!.RoleAppService_roleByNameRequest\x1a\".RoleAppService_roleByNameResponse\"\x00\x32\x8b\x01\n\x14PermissionAppService\x12s\n\x10permissionByName\x12-.PermissionAppService_permissionByNameRequest\x1a..PermissionAppService_permissionByNameResponse\"\x00\x32[\n\x0cOuAppService\x12K\n\x08ouByName\x12\x1d.OuAppService_ouByNameRequest\x1a\x1e.OuAppService_ouByNameResponse\"\x00\x32m\n\x0fRealmAppService\x12Z\n\x0brealmByName\x12#.RealmAppService_realmByNameRequest\x1a$.RealmAppService_realmByNameResponse\"\x00\x62\x06proto3'
)




_USERAPPSERVICE_USERBYUSERNAMEANDPASSWORDREQUEST = _descriptor.Descriptor(
  name='UserAppService_userByUsernameAndPasswordRequest',
  full_name='UserAppService_userByUsernameAndPasswordRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='UserAppService_userByUsernameAndPasswordRequest.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='UserAppService_userByUsernameAndPasswordRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=103,
)


_USERAPPSERVICE_USERBYUSERNAMEANDPASSWORDRESPONSE = _descriptor.Descriptor(
  name='UserAppService_userByUsernameAndPasswordResponse',
  full_name='UserAppService_userByUsernameAndPasswordResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='UserAppService_userByUsernameAndPasswordResponse.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='username', full_name='UserAppService_userByUsernameAndPasswordResponse.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='UserAppService_userByUsernameAndPasswordResponse.password', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=203,
)


_ROLEAPPSERVICE_ROLEBYNAMEREQUEST = _descriptor.Descriptor(
  name='RoleAppService_roleByNameRequest',
  full_name='RoleAppService_roleByNameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='RoleAppService_roleByNameRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=253,
)


_ROLEAPPSERVICE_ROLEBYNAMERESPONSE = _descriptor.Descriptor(
  name='RoleAppService_roleByNameResponse',
  full_name='RoleAppService_roleByNameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='RoleAppService_roleByNameResponse.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='RoleAppService_roleByNameResponse.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=255,
  serialized_end=316,
)


_PERMISSIONAPPSERVICE_PERMISSIONBYNAMEREQUEST = _descriptor.Descriptor(
  name='PermissionAppService_permissionByNameRequest',
  full_name='PermissionAppService_permissionByNameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='PermissionAppService_permissionByNameRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=318,
  serialized_end=378,
)


_PERMISSIONAPPSERVICE_PERMISSIONBYNAMERESPONSE = _descriptor.Descriptor(
  name='PermissionAppService_permissionByNameResponse',
  full_name='PermissionAppService_permissionByNameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='PermissionAppService_permissionByNameResponse.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='PermissionAppService_permissionByNameResponse.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=380,
  serialized_end=453,
)


_OUAPPSERVICE_OUBYNAMEREQUEST = _descriptor.Descriptor(
  name='OuAppService_ouByNameRequest',
  full_name='OuAppService_ouByNameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='OuAppService_ouByNameRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=455,
  serialized_end=499,
)


_OUAPPSERVICE_OUBYNAMERESPONSE = _descriptor.Descriptor(
  name='OuAppService_ouByNameResponse',
  full_name='OuAppService_ouByNameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='OuAppService_ouByNameResponse.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='OuAppService_ouByNameResponse.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=501,
  serialized_end=558,
)


_REALMAPPSERVICE_REALMBYNAMEREQUEST = _descriptor.Descriptor(
  name='RealmAppService_realmByNameRequest',
  full_name='RealmAppService_realmByNameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='RealmAppService_realmByNameRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=560,
  serialized_end=610,
)


_REALMAPPSERVICE_REALMBYNAMERESPONSE = _descriptor.Descriptor(
  name='RealmAppService_realmByNameResponse',
  full_name='RealmAppService_realmByNameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='RealmAppService_realmByNameResponse.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='RealmAppService_realmByNameResponse.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=612,
  serialized_end=675,
)

DESCRIPTOR.message_types_by_name['UserAppService_userByUsernameAndPasswordRequest'] = _USERAPPSERVICE_USERBYUSERNAMEANDPASSWORDREQUEST
DESCRIPTOR.message_types_by_name['UserAppService_userByUsernameAndPasswordResponse'] = _USERAPPSERVICE_USERBYUSERNAMEANDPASSWORDRESPONSE
DESCRIPTOR.message_types_by_name['RoleAppService_roleByNameRequest'] = _ROLEAPPSERVICE_ROLEBYNAMEREQUEST
DESCRIPTOR.message_types_by_name['RoleAppService_roleByNameResponse'] = _ROLEAPPSERVICE_ROLEBYNAMERESPONSE
DESCRIPTOR.message_types_by_name['PermissionAppService_permissionByNameRequest'] = _PERMISSIONAPPSERVICE_PERMISSIONBYNAMEREQUEST
DESCRIPTOR.message_types_by_name['PermissionAppService_permissionByNameResponse'] = _PERMISSIONAPPSERVICE_PERMISSIONBYNAMERESPONSE
DESCRIPTOR.message_types_by_name['OuAppService_ouByNameRequest'] = _OUAPPSERVICE_OUBYNAMEREQUEST
DESCRIPTOR.message_types_by_name['OuAppService_ouByNameResponse'] = _OUAPPSERVICE_OUBYNAMERESPONSE
DESCRIPTOR.message_types_by_name['RealmAppService_realmByNameRequest'] = _REALMAPPSERVICE_REALMBYNAMEREQUEST
DESCRIPTOR.message_types_by_name['RealmAppService_realmByNameResponse'] = _REALMAPPSERVICE_REALMBYNAMERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserAppService_userByUsernameAndPasswordRequest = _reflection.GeneratedProtocolMessageType('UserAppService_userByUsernameAndPasswordRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERAPPSERVICE_USERBYUSERNAMEANDPASSWORDREQUEST,
  '__module__' : 'identity_pb2'
  # @@protoc_insertion_point(class_scope:UserAppService_userByUsernameAndPasswordRequest)
  })
_sym_db.RegisterMessage(UserAppService_userByUsernameAndPasswordRequest)

UserAppService_userByUsernameAndPasswordResponse = _reflection.GeneratedProtocolMessageType('UserAppService_userByUsernameAndPasswordResponse', (_message.Message,), {
  'DESCRIPTOR' : _USERAPPSERVICE_USERBYUSERNAMEANDPASSWORDRESPONSE,
  '__module__' : 'identity_pb2'
  # @@protoc_insertion_point(class_scope:UserAppService_userByUsernameAndPasswordResponse)
  })
_sym_db.RegisterMessage(UserAppService_userByUsernameAndPasswordResponse)

RoleAppService_roleByNameRequest = _reflection.GeneratedProtocolMessageType('RoleAppService_roleByNameRequest', (_message.Message,), {
  'DESCRIPTOR' : _ROLEAPPSERVICE_ROLEBYNAMEREQUEST,
  '__module__' : 'identity_pb2'
  # @@protoc_insertion_point(class_scope:RoleAppService_roleByNameRequest)
  })
_sym_db.RegisterMessage(RoleAppService_roleByNameRequest)

RoleAppService_roleByNameResponse = _reflection.GeneratedProtocolMessageType('RoleAppService_roleByNameResponse', (_message.Message,), {
  'DESCRIPTOR' : _ROLEAPPSERVICE_ROLEBYNAMERESPONSE,
  '__module__' : 'identity_pb2'
  # @@protoc_insertion_point(class_scope:RoleAppService_roleByNameResponse)
  })
_sym_db.RegisterMessage(RoleAppService_roleByNameResponse)

PermissionAppService_permissionByNameRequest = _reflection.GeneratedProtocolMessageType('PermissionAppService_permissionByNameRequest', (_message.Message,), {
  'DESCRIPTOR' : _PERMISSIONAPPSERVICE_PERMISSIONBYNAMEREQUEST,
  '__module__' : 'identity_pb2'
  # @@protoc_insertion_point(class_scope:PermissionAppService_permissionByNameRequest)
  })
_sym_db.RegisterMessage(PermissionAppService_permissionByNameRequest)

PermissionAppService_permissionByNameResponse = _reflection.GeneratedProtocolMessageType('PermissionAppService_permissionByNameResponse', (_message.Message,), {
  'DESCRIPTOR' : _PERMISSIONAPPSERVICE_PERMISSIONBYNAMERESPONSE,
  '__module__' : 'identity_pb2'
  # @@protoc_insertion_point(class_scope:PermissionAppService_permissionByNameResponse)
  })
_sym_db.RegisterMessage(PermissionAppService_permissionByNameResponse)

OuAppService_ouByNameRequest = _reflection.GeneratedProtocolMessageType('OuAppService_ouByNameRequest', (_message.Message,), {
  'DESCRIPTOR' : _OUAPPSERVICE_OUBYNAMEREQUEST,
  '__module__' : 'identity_pb2'
  # @@protoc_insertion_point(class_scope:OuAppService_ouByNameRequest)
  })
_sym_db.RegisterMessage(OuAppService_ouByNameRequest)

OuAppService_ouByNameResponse = _reflection.GeneratedProtocolMessageType('OuAppService_ouByNameResponse', (_message.Message,), {
  'DESCRIPTOR' : _OUAPPSERVICE_OUBYNAMERESPONSE,
  '__module__' : 'identity_pb2'
  # @@protoc_insertion_point(class_scope:OuAppService_ouByNameResponse)
  })
_sym_db.RegisterMessage(OuAppService_ouByNameResponse)

RealmAppService_realmByNameRequest = _reflection.GeneratedProtocolMessageType('RealmAppService_realmByNameRequest', (_message.Message,), {
  'DESCRIPTOR' : _REALMAPPSERVICE_REALMBYNAMEREQUEST,
  '__module__' : 'identity_pb2'
  # @@protoc_insertion_point(class_scope:RealmAppService_realmByNameRequest)
  })
_sym_db.RegisterMessage(RealmAppService_realmByNameRequest)

RealmAppService_realmByNameResponse = _reflection.GeneratedProtocolMessageType('RealmAppService_realmByNameResponse', (_message.Message,), {
  'DESCRIPTOR' : _REALMAPPSERVICE_REALMBYNAMERESPONSE,
  '__module__' : 'identity_pb2'
  # @@protoc_insertion_point(class_scope:RealmAppService_realmByNameResponse)
  })
_sym_db.RegisterMessage(RealmAppService_realmByNameResponse)



_USERAPPSERVICE = _descriptor.ServiceDescriptor(
  name='UserAppService',
  full_name='UserAppService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=678,
  serialized_end=827,
  methods=[
  _descriptor.MethodDescriptor(
    name='userByUsernameAndPassword',
    full_name='UserAppService.userByUsernameAndPassword',
    index=0,
    containing_service=None,
    input_type=_USERAPPSERVICE_USERBYUSERNAMEANDPASSWORDREQUEST,
    output_type=_USERAPPSERVICE_USERBYUSERNAMEANDPASSWORDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_USERAPPSERVICE)

DESCRIPTOR.services_by_name['UserAppService'] = _USERAPPSERVICE


_ROLEAPPSERVICE = _descriptor.ServiceDescriptor(
  name='RoleAppService',
  full_name='RoleAppService',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=829,
  serialized_end=932,
  methods=[
  _descriptor.MethodDescriptor(
    name='roleByName',
    full_name='RoleAppService.roleByName',
    index=0,
    containing_service=None,
    input_type=_ROLEAPPSERVICE_ROLEBYNAMEREQUEST,
    output_type=_ROLEAPPSERVICE_ROLEBYNAMERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ROLEAPPSERVICE)

DESCRIPTOR.services_by_name['RoleAppService'] = _ROLEAPPSERVICE


_PERMISSIONAPPSERVICE = _descriptor.ServiceDescriptor(
  name='PermissionAppService',
  full_name='PermissionAppService',
  file=DESCRIPTOR,
  index=2,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=935,
  serialized_end=1074,
  methods=[
  _descriptor.MethodDescriptor(
    name='permissionByName',
    full_name='PermissionAppService.permissionByName',
    index=0,
    containing_service=None,
    input_type=_PERMISSIONAPPSERVICE_PERMISSIONBYNAMEREQUEST,
    output_type=_PERMISSIONAPPSERVICE_PERMISSIONBYNAMERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PERMISSIONAPPSERVICE)

DESCRIPTOR.services_by_name['PermissionAppService'] = _PERMISSIONAPPSERVICE


_OUAPPSERVICE = _descriptor.ServiceDescriptor(
  name='OuAppService',
  full_name='OuAppService',
  file=DESCRIPTOR,
  index=3,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=1076,
  serialized_end=1167,
  methods=[
  _descriptor.MethodDescriptor(
    name='ouByName',
    full_name='OuAppService.ouByName',
    index=0,
    containing_service=None,
    input_type=_OUAPPSERVICE_OUBYNAMEREQUEST,
    output_type=_OUAPPSERVICE_OUBYNAMERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_OUAPPSERVICE)

DESCRIPTOR.services_by_name['OuAppService'] = _OUAPPSERVICE


_REALMAPPSERVICE = _descriptor.ServiceDescriptor(
  name='RealmAppService',
  full_name='RealmAppService',
  file=DESCRIPTOR,
  index=4,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=1169,
  serialized_end=1278,
  methods=[
  _descriptor.MethodDescriptor(
    name='realmByName',
    full_name='RealmAppService.realmByName',
    index=0,
    containing_service=None,
    input_type=_REALMAPPSERVICE_REALMBYNAMEREQUEST,
    output_type=_REALMAPPSERVICE_REALMBYNAMERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_REALMAPPSERVICE)

DESCRIPTOR.services_by_name['RealmAppService'] = _REALMAPPSERVICE

# @@protoc_insertion_point(module_scope)
