# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ou_app_service_pb2 as ou__app__service__pb2


class OuAppServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ouByName = channel.unary_unary(
                '/cafm.identity.ou.OuAppService/ouByName',
                request_serializer=ou__app__service__pb2.OuAppService_ouByNameRequest.SerializeToString,
                response_deserializer=ou__app__service__pb2.OuAppService_ouByNameResponse.FromString,
                )
        self.ouById = channel.unary_unary(
                '/cafm.identity.ou.OuAppService/ouById',
                request_serializer=ou__app__service__pb2.OuAppService_ouByIdRequest.SerializeToString,
                response_deserializer=ou__app__service__pb2.OuAppService_ouByIdResponse.FromString,
                )
        self.ous = channel.unary_unary(
                '/cafm.identity.ou.OuAppService/ous',
                request_serializer=ou__app__service__pb2.OuAppService_ousRequest.SerializeToString,
                response_deserializer=ou__app__service__pb2.OuAppService_ousResponse.FromString,
                )


class OuAppServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ouByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ouById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ous(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OuAppServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ouByName': grpc.unary_unary_rpc_method_handler(
                    servicer.ouByName,
                    request_deserializer=ou__app__service__pb2.OuAppService_ouByNameRequest.FromString,
                    response_serializer=ou__app__service__pb2.OuAppService_ouByNameResponse.SerializeToString,
            ),
            'ouById': grpc.unary_unary_rpc_method_handler(
                    servicer.ouById,
                    request_deserializer=ou__app__service__pb2.OuAppService_ouByIdRequest.FromString,
                    response_serializer=ou__app__service__pb2.OuAppService_ouByIdResponse.SerializeToString,
            ),
            'ous': grpc.unary_unary_rpc_method_handler(
                    servicer.ous,
                    request_deserializer=ou__app__service__pb2.OuAppService_ousRequest.FromString,
                    response_serializer=ou__app__service__pb2.OuAppService_ousResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cafm.identity.ou.OuAppService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OuAppService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ouByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cafm.identity.ou.OuAppService/ouByName',
            ou__app__service__pb2.OuAppService_ouByNameRequest.SerializeToString,
            ou__app__service__pb2.OuAppService_ouByNameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ouById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cafm.identity.ou.OuAppService/ouById',
            ou__app__service__pb2.OuAppService_ouByIdRequest.SerializeToString,
            ou__app__service__pb2.OuAppService_ouByIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ous(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cafm.identity.ou.OuAppService/ous',
            ou__app__service__pb2.OuAppService_ousRequest.SerializeToString,
            ou__app__service__pb2.OuAppService_ousResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
