# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import permission_app_service_pb2 as permission__app__service__pb2


class PermissionAppServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.permissionByName = channel.unary_unary(
                '/coral.identity.permission.PermissionAppService/permissionByName',
                request_serializer=permission__app__service__pb2.PermissionAppService_permissionByNameRequest.SerializeToString,
                response_deserializer=permission__app__service__pb2.PermissionAppService_permissionByNameResponse.FromString,
                )


class PermissionAppServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def permissionByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PermissionAppServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'permissionByName': grpc.unary_unary_rpc_method_handler(
                    servicer.permissionByName,
                    request_deserializer=permission__app__service__pb2.PermissionAppService_permissionByNameRequest.FromString,
                    response_serializer=permission__app__service__pb2.PermissionAppService_permissionByNameResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coral.identity.permission.PermissionAppService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PermissionAppService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def permissionByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coral.identity.permission.PermissionAppService/permissionByName',
            permission__app__service__pb2.PermissionAppService_permissionByNameRequest.SerializeToString,
            permission__app__service__pb2.PermissionAppService_permissionByNameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
