# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permission_context_app_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import permission_context_pb2 as permission__context__pb2
import order_pb2 as order__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='permission_context_app_service.proto',
  package='cafm.identity.permission',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n$permission_context_app_service.proto\x12\x18\x63\x61\x66m.identity.permission\x1a\x18permission_context.proto\x1a\x0border.proto\"F\n8PermissionContextAppService_permissionContextByIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x83\x01\n9PermissionContextAppService_permissionContextByIdResponse\x12\x46\n\x11permissionContext\x18\x01 \x01(\x0b\x32+.cafm.identity.permission.PermissionContext\"\x88\x01\n5PermissionContextAppService_permissionContextsRequest\x12\x12\n\nresultFrom\x18\x01 \x01(\x05\x12\x12\n\nresultSize\x18\x02 \x01(\x05\x12\'\n\x05order\x18\x03 \x03(\x0b\x32\x18.cafm.common.order.Order\"\x94\x01\n6PermissionContextAppService_permissionContextsResponse\x12G\n\x12permissionContexts\x18\x01 \x03(\x0b\x32+.cafm.identity.permission.PermissionContext\x12\x11\n\titemCount\x18\x02 \x01(\x05\x32\x9e\x03\n\x1bPermissionContextAppService\x12\xc2\x01\n\x15permissionContextById\x12R.cafm.identity.permission.PermissionContextAppService_permissionContextByIdRequest\x1aS.cafm.identity.permission.PermissionContextAppService_permissionContextByIdResponse\"\x00\x12\xb9\x01\n\x12permissionContexts\x12O.cafm.identity.permission.PermissionContextAppService_permissionContextsRequest\x1aP.cafm.identity.permission.PermissionContextAppService_permissionContextsResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[permission__context__pb2.DESCRIPTOR,order__pb2.DESCRIPTOR,])




_PERMISSIONCONTEXTAPPSERVICE_PERMISSIONCONTEXTBYIDREQUEST = _descriptor.Descriptor(
  name='PermissionContextAppService_permissionContextByIdRequest',
  full_name='cafm.identity.permission.PermissionContextAppService_permissionContextByIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='cafm.identity.permission.PermissionContextAppService_permissionContextByIdRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=175,
)


_PERMISSIONCONTEXTAPPSERVICE_PERMISSIONCONTEXTBYIDRESPONSE = _descriptor.Descriptor(
  name='PermissionContextAppService_permissionContextByIdResponse',
  full_name='cafm.identity.permission.PermissionContextAppService_permissionContextByIdResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='permissionContext', full_name='cafm.identity.permission.PermissionContextAppService_permissionContextByIdResponse.permissionContext', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=309,
)


_PERMISSIONCONTEXTAPPSERVICE_PERMISSIONCONTEXTSREQUEST = _descriptor.Descriptor(
  name='PermissionContextAppService_permissionContextsRequest',
  full_name='cafm.identity.permission.PermissionContextAppService_permissionContextsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='resultFrom', full_name='cafm.identity.permission.PermissionContextAppService_permissionContextsRequest.resultFrom', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resultSize', full_name='cafm.identity.permission.PermissionContextAppService_permissionContextsRequest.resultSize', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='order', full_name='cafm.identity.permission.PermissionContextAppService_permissionContextsRequest.order', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=312,
  serialized_end=448,
)


_PERMISSIONCONTEXTAPPSERVICE_PERMISSIONCONTEXTSRESPONSE = _descriptor.Descriptor(
  name='PermissionContextAppService_permissionContextsResponse',
  full_name='cafm.identity.permission.PermissionContextAppService_permissionContextsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='permissionContexts', full_name='cafm.identity.permission.PermissionContextAppService_permissionContextsResponse.permissionContexts', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='itemCount', full_name='cafm.identity.permission.PermissionContextAppService_permissionContextsResponse.itemCount', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=451,
  serialized_end=599,
)

_PERMISSIONCONTEXTAPPSERVICE_PERMISSIONCONTEXTBYIDRESPONSE.fields_by_name['permissionContext'].message_type = permission__context__pb2._PERMISSIONCONTEXT
_PERMISSIONCONTEXTAPPSERVICE_PERMISSIONCONTEXTSREQUEST.fields_by_name['order'].message_type = order__pb2._ORDER
_PERMISSIONCONTEXTAPPSERVICE_PERMISSIONCONTEXTSRESPONSE.fields_by_name['permissionContexts'].message_type = permission__context__pb2._PERMISSIONCONTEXT
DESCRIPTOR.message_types_by_name['PermissionContextAppService_permissionContextByIdRequest'] = _PERMISSIONCONTEXTAPPSERVICE_PERMISSIONCONTEXTBYIDREQUEST
DESCRIPTOR.message_types_by_name['PermissionContextAppService_permissionContextByIdResponse'] = _PERMISSIONCONTEXTAPPSERVICE_PERMISSIONCONTEXTBYIDRESPONSE
DESCRIPTOR.message_types_by_name['PermissionContextAppService_permissionContextsRequest'] = _PERMISSIONCONTEXTAPPSERVICE_PERMISSIONCONTEXTSREQUEST
DESCRIPTOR.message_types_by_name['PermissionContextAppService_permissionContextsResponse'] = _PERMISSIONCONTEXTAPPSERVICE_PERMISSIONCONTEXTSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PermissionContextAppService_permissionContextByIdRequest = _reflection.GeneratedProtocolMessageType('PermissionContextAppService_permissionContextByIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _PERMISSIONCONTEXTAPPSERVICE_PERMISSIONCONTEXTBYIDREQUEST,
  '__module__' : 'permission_context_app_service_pb2'
  # @@protoc_insertion_point(class_scope:cafm.identity.permission.PermissionContextAppService_permissionContextByIdRequest)
  })
_sym_db.RegisterMessage(PermissionContextAppService_permissionContextByIdRequest)

PermissionContextAppService_permissionContextByIdResponse = _reflection.GeneratedProtocolMessageType('PermissionContextAppService_permissionContextByIdResponse', (_message.Message,), {
  'DESCRIPTOR' : _PERMISSIONCONTEXTAPPSERVICE_PERMISSIONCONTEXTBYIDRESPONSE,
  '__module__' : 'permission_context_app_service_pb2'
  # @@protoc_insertion_point(class_scope:cafm.identity.permission.PermissionContextAppService_permissionContextByIdResponse)
  })
_sym_db.RegisterMessage(PermissionContextAppService_permissionContextByIdResponse)

PermissionContextAppService_permissionContextsRequest = _reflection.GeneratedProtocolMessageType('PermissionContextAppService_permissionContextsRequest', (_message.Message,), {
  'DESCRIPTOR' : _PERMISSIONCONTEXTAPPSERVICE_PERMISSIONCONTEXTSREQUEST,
  '__module__' : 'permission_context_app_service_pb2'
  # @@protoc_insertion_point(class_scope:cafm.identity.permission.PermissionContextAppService_permissionContextsRequest)
  })
_sym_db.RegisterMessage(PermissionContextAppService_permissionContextsRequest)

PermissionContextAppService_permissionContextsResponse = _reflection.GeneratedProtocolMessageType('PermissionContextAppService_permissionContextsResponse', (_message.Message,), {
  'DESCRIPTOR' : _PERMISSIONCONTEXTAPPSERVICE_PERMISSIONCONTEXTSRESPONSE,
  '__module__' : 'permission_context_app_service_pb2'
  # @@protoc_insertion_point(class_scope:cafm.identity.permission.PermissionContextAppService_permissionContextsResponse)
  })
_sym_db.RegisterMessage(PermissionContextAppService_permissionContextsResponse)



_PERMISSIONCONTEXTAPPSERVICE = _descriptor.ServiceDescriptor(
  name='PermissionContextAppService',
  full_name='cafm.identity.permission.PermissionContextAppService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=602,
  serialized_end=1016,
  methods=[
  _descriptor.MethodDescriptor(
    name='permissionContextById',
    full_name='cafm.identity.permission.PermissionContextAppService.permissionContextById',
    index=0,
    containing_service=None,
    input_type=_PERMISSIONCONTEXTAPPSERVICE_PERMISSIONCONTEXTBYIDREQUEST,
    output_type=_PERMISSIONCONTEXTAPPSERVICE_PERMISSIONCONTEXTBYIDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='permissionContexts',
    full_name='cafm.identity.permission.PermissionContextAppService.permissionContexts',
    index=1,
    containing_service=None,
    input_type=_PERMISSIONCONTEXTAPPSERVICE_PERMISSIONCONTEXTSREQUEST,
    output_type=_PERMISSIONCONTEXTAPPSERVICE_PERMISSIONCONTEXTSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PERMISSIONCONTEXTAPPSERVICE)

DESCRIPTOR.services_by_name['PermissionContextAppService'] = _PERMISSIONCONTEXTAPPSERVICE

# @@protoc_insertion_point(module_scope)
