# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import realm_app_service_pb2 as realm__app__service__pb2


class RealmAppServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.realmByName = channel.unary_unary(
                '/cafm.identity.realm.RealmAppService/realmByName',
                request_serializer=realm__app__service__pb2.RealmAppService_realmByNameRequest.SerializeToString,
                response_deserializer=realm__app__service__pb2.RealmAppService_realmByNameResponse.FromString,
                )


class RealmAppServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def realmByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RealmAppServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'realmByName': grpc.unary_unary_rpc_method_handler(
                    servicer.realmByName,
                    request_deserializer=realm__app__service__pb2.RealmAppService_realmByNameRequest.FromString,
                    response_serializer=realm__app__service__pb2.RealmAppService_realmByNameResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cafm.identity.realm.RealmAppService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RealmAppService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def realmByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cafm.identity.realm.RealmAppService/realmByName',
            realm__app__service__pb2.RealmAppService_realmByNameRequest.SerializeToString,
            realm__app__service__pb2.RealmAppService_realmByNameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
