# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import resource_type_app_service_pb2 as resource__type__app__service__pb2


class ResourceTypeAppServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.resourceTypeByName = channel.unary_unary(
                '/cafm.identity.resourceType.ResourceTypeAppService/resourceTypeByName',
                request_serializer=resource__type__app__service__pb2.ResourceTypeAppService_resourceTypeByNameRequest.SerializeToString,
                response_deserializer=resource__type__app__service__pb2.ResourceTypeAppService_resourceTypeByNameResponse.FromString,
                )
        self.resourceTypes = channel.unary_unary(
                '/cafm.identity.resourceType.ResourceTypeAppService/resourceTypes',
                request_serializer=resource__type__app__service__pb2.ResourceTypeAppService_resourceTypesRequest.SerializeToString,
                response_deserializer=resource__type__app__service__pb2.ResourceTypeAppService_resourceTypesResponse.FromString,
                )


class ResourceTypeAppServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def resourceTypeByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def resourceTypes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ResourceTypeAppServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'resourceTypeByName': grpc.unary_unary_rpc_method_handler(
                    servicer.resourceTypeByName,
                    request_deserializer=resource__type__app__service__pb2.ResourceTypeAppService_resourceTypeByNameRequest.FromString,
                    response_serializer=resource__type__app__service__pb2.ResourceTypeAppService_resourceTypeByNameResponse.SerializeToString,
            ),
            'resourceTypes': grpc.unary_unary_rpc_method_handler(
                    servicer.resourceTypes,
                    request_deserializer=resource__type__app__service__pb2.ResourceTypeAppService_resourceTypesRequest.FromString,
                    response_serializer=resource__type__app__service__pb2.ResourceTypeAppService_resourceTypesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cafm.identity.resourceType.ResourceTypeAppService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ResourceTypeAppService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def resourceTypeByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cafm.identity.resourceType.ResourceTypeAppService/resourceTypeByName',
            resource__type__app__service__pb2.ResourceTypeAppService_resourceTypeByNameRequest.SerializeToString,
            resource__type__app__service__pb2.ResourceTypeAppService_resourceTypeByNameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def resourceTypes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cafm.identity.resourceType.ResourceTypeAppService/resourceTypes',
            resource__type__app__service__pb2.ResourceTypeAppService_resourceTypesRequest.SerializeToString,
            resource__type__app__service__pb2.ResourceTypeAppService_resourceTypesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
