# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import permission_context_app_service_pb2 as resource__type__app__service__pb2


class PermissionContextAppServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.permissionContextByName = channel.unary_unary(
                '/cafm.identity.permission_context.PermissionContextAppService/permissionContextByName',
                request_serializer=resource__type__app__service__pb2.PermissionContextAppService_permissionContextByNameRequest.SerializeToString,
                response_deserializer=resource__type__app__service__pb2.PermissionContextAppService_permissionContextByNameResponse.FromString,
                )
        self.permissionContextById = channel.unary_unary(
                '/cafm.identity.permission_context.PermissionContextAppService/permissionContextById',
                request_serializer=resource__type__app__service__pb2.PermissionContextAppService_permissionContextByIdRequest.SerializeToString,
                response_deserializer=resource__type__app__service__pb2.PermissionContextAppService_permissionContextByIdResponse.FromString,
                )
        self.permissionContexts = channel.unary_unary(
                '/cafm.identity.permission_context.PermissionContextAppService/permissionContexts',
                request_serializer=resource__type__app__service__pb2.PermissionContextAppService_permissionContextsRequest.SerializeToString,
                response_deserializer=resource__type__app__service__pb2.PermissionContextAppService_permissionContextsResponse.FromString,
                )


class PermissionContextAppServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def permissionContextByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def permissionContextById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def permissionContexts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PermissionContextAppServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'permissionContextByName': grpc.unary_unary_rpc_method_handler(
                    servicer.permissionContextByName,
                    request_deserializer=resource__type__app__service__pb2.PermissionContextAppService_permissionContextByNameRequest.FromString,
                    response_serializer=resource__type__app__service__pb2.PermissionContextAppService_permissionContextByNameResponse.SerializeToString,
            ),
            'permissionContextById': grpc.unary_unary_rpc_method_handler(
                    servicer.permissionContextById,
                    request_deserializer=resource__type__app__service__pb2.PermissionContextAppService_permissionContextByIdRequest.FromString,
                    response_serializer=resource__type__app__service__pb2.PermissionContextAppService_permissionContextByIdResponse.SerializeToString,
            ),
            'permissionContexts': grpc.unary_unary_rpc_method_handler(
                    servicer.permissionContexts,
                    request_deserializer=resource__type__app__service__pb2.PermissionContextAppService_permissionContextsRequest.FromString,
                    response_serializer=resource__type__app__service__pb2.PermissionContextAppService_permissionContextsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cafm.identity.permission_context.PermissionContextAppService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PermissionContextAppService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def permissionContextByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cafm.identity.permission_context.PermissionContextAppService/permissionContextByName',
            resource__type__app__service__pb2.PermissionContextAppService_permissionContextByNameRequest.SerializeToString,
            resource__type__app__service__pb2.PermissionContextAppService_permissionContextByNameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def permissionContextById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cafm.identity.permission_context.PermissionContextAppService/permissionContextById',
            resource__type__app__service__pb2.PermissionContextAppService_permissionContextByIdRequest.SerializeToString,
            resource__type__app__service__pb2.PermissionContextAppService_permissionContextByIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def permissionContexts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cafm.identity.permission_context.PermissionContextAppService/permissionContexts',
            resource__type__app__service__pb2.PermissionContextAppService_permissionContextsRequest.SerializeToString,
            resource__type__app__service__pb2.PermissionContextAppService_permissionContextsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
