# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permission_context_app_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import permission_context_pb2 as resource__type__pb2
import order_pb2 as order__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='permission_context_app_service.proto',
  package='cafm.identity.permission_context',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1fpermission_context_app_service.proto\x12\x1b\x63\x61\x66m.identity.permission_context\x1a\x13permission_context.proto\x1a\x0border.proto\"@\n0PermissionContextAppService_permissionContextByNameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"t\n1PermissionContextAppService_permissionContextByNameResponse\x12?\n\x0cpermissionContext\x18\x01 \x01(\x0b\x32).cafm.identity.permission_context.PermissionContext\"<\n.PermissionContextAppService_permissionContextByIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"r\n/PermissionContextAppService_permissionContextByIdResponse\x12?\n\x0cpermissionContext\x18\x01 \x01(\x0b\x32).cafm.identity.permission_context.PermissionContext\"\x80\x01\n+PermissionContextAppService_permissionContextsRequest\x12\x12\n\nresultFrom\x18\x01 \x01(\x05\x12\x12\n\nresultSize\x18\x02 \x01(\x05\x12)\n\x05order\x18\x03 \x03(\x0b\x32\x1a.cafm.identity.order.Order\"\x83\x01\n,PermissionContextAppService_permissionContextsResponse\x12@\n\rpermissionContexts\x18\x01 \x03(\x0b\x32).cafm.identity.permission_context.PermissionContext\x12\x11\n\titemCount\x18\x02 \x01(\x05\x32\xab\x04\n\x16PermissionContextAppService\x12\xb5\x01\n\x12permissionContextByName\x12M.cafm.identity.permission_context.PermissionContextAppService_permissionContextByNameRequest\x1aN.cafm.identity.permission_context.PermissionContextAppService_permissionContextByNameResponse\"\x00\x12\xaf\x01\n\x10permissionContextById\x12K.cafm.identity.permission_context.PermissionContextAppService_permissionContextByIdRequest\x1aL.cafm.identity.permission_context.PermissionContextAppService_permissionContextByIdResponse\"\x00\x12\xa6\x01\n\rpermissionContexts\x12H.cafm.identity.permission_context.PermissionContextAppService_permissionContextsRequest\x1aI.cafm.identity.permission_context.PermissionContextAppService_permissionContextsResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[resource__type__pb2.DESCRIPTOR,order__pb2.DESCRIPTOR,])




_RESOURCETYPEAPPSERVICE_RESOURCETYPEBYNAMEREQUEST = _descriptor.Descriptor(
  name='PermissionContextAppService_permissionContextByNameRequest',
  full_name='cafm.identity.permission_context.PermissionContextAppService_permissionContextByNameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='cafm.identity.permission_context.PermissionContextAppService_permissionContextByNameRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=162,
)


_RESOURCETYPEAPPSERVICE_RESOURCETYPEBYNAMERESPONSE = _descriptor.Descriptor(
  name='PermissionContextAppService_permissionContextByNameResponse',
  full_name='cafm.identity.permission_context.PermissionContextAppService_permissionContextByNameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='permissionContext', full_name='cafm.identity.permission_context.PermissionContextAppService_permissionContextByNameResponse.permissionContext', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=280,
)


_RESOURCETYPEAPPSERVICE_RESOURCETYPEBYIDREQUEST = _descriptor.Descriptor(
  name='PermissionContextAppService_permissionContextByIdRequest',
  full_name='cafm.identity.permission_context.PermissionContextAppService_permissionContextByIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='cafm.identity.permission_context.PermissionContextAppService_permissionContextByIdRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=342,
)


_RESOURCETYPEAPPSERVICE_RESOURCETYPEBYIDRESPONSE = _descriptor.Descriptor(
  name='PermissionContextAppService_permissionContextByIdResponse',
  full_name='cafm.identity.permission_context.PermissionContextAppService_permissionContextByIdResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='permissionContext', full_name='cafm.identity.permission_context.PermissionContextAppService_permissionContextByIdResponse.permissionContext', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=344,
  serialized_end=458,
)


_RESOURCETYPEAPPSERVICE_RESOURCETYPESREQUEST = _descriptor.Descriptor(
  name='PermissionContextAppService_permissionContextsRequest',
  full_name='cafm.identity.permission_context.PermissionContextAppService_permissionContextsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='resultFrom', full_name='cafm.identity.permission_context.PermissionContextAppService_permissionContextsRequest.resultFrom', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resultSize', full_name='cafm.identity.permission_context.PermissionContextAppService_permissionContextsRequest.resultSize', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='order', full_name='cafm.identity.permission_context.PermissionContextAppService_permissionContextsRequest.order', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=461,
  serialized_end=589,
)


_RESOURCETYPEAPPSERVICE_RESOURCETYPESRESPONSE = _descriptor.Descriptor(
  name='PermissionContextAppService_permissionContextsResponse',
  full_name='cafm.identity.permission_context.PermissionContextAppService_permissionContextsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='permissionContexts', full_name='cafm.identity.permission_context.PermissionContextAppService_permissionContextsResponse.permissionContexts', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='itemCount', full_name='cafm.identity.permission_context.PermissionContextAppService_permissionContextsResponse.itemCount', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=592,
  serialized_end=723,
)

_RESOURCETYPEAPPSERVICE_RESOURCETYPEBYNAMERESPONSE.fields_by_name['permissionContext'].message_type = resource__type__pb2._RESOURCETYPE
_RESOURCETYPEAPPSERVICE_RESOURCETYPEBYIDRESPONSE.fields_by_name['permissionContext'].message_type = resource__type__pb2._RESOURCETYPE
_RESOURCETYPEAPPSERVICE_RESOURCETYPESREQUEST.fields_by_name['order'].message_type = order__pb2._ORDER
_RESOURCETYPEAPPSERVICE_RESOURCETYPESRESPONSE.fields_by_name['permissionContexts'].message_type = resource__type__pb2._RESOURCETYPE
DESCRIPTOR.message_types_by_name['PermissionContextAppService_permissionContextByNameRequest'] = _RESOURCETYPEAPPSERVICE_RESOURCETYPEBYNAMEREQUEST
DESCRIPTOR.message_types_by_name['PermissionContextAppService_permissionContextByNameResponse'] = _RESOURCETYPEAPPSERVICE_RESOURCETYPEBYNAMERESPONSE
DESCRIPTOR.message_types_by_name['PermissionContextAppService_permissionContextByIdRequest'] = _RESOURCETYPEAPPSERVICE_RESOURCETYPEBYIDREQUEST
DESCRIPTOR.message_types_by_name['PermissionContextAppService_permissionContextByIdResponse'] = _RESOURCETYPEAPPSERVICE_RESOURCETYPEBYIDRESPONSE
DESCRIPTOR.message_types_by_name['PermissionContextAppService_permissionContextsRequest'] = _RESOURCETYPEAPPSERVICE_RESOURCETYPESREQUEST
DESCRIPTOR.message_types_by_name['PermissionContextAppService_permissionContextsResponse'] = _RESOURCETYPEAPPSERVICE_RESOURCETYPESRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PermissionContextAppService_permissionContextByNameRequest = _reflection.GeneratedProtocolMessageType('PermissionContextAppService_permissionContextByNameRequest', (_message.Message,), {
  'DESCRIPTOR' : _RESOURCETYPEAPPSERVICE_RESOURCETYPEBYNAMEREQUEST,
  '__module__' : 'permission_context_app_service_pb2'
  # @@protoc_insertion_point(class_scope:cafm.identity.permission_context.PermissionContextAppService_permissionContextByNameRequest)
  })
_sym_db.RegisterMessage(PermissionContextAppService_permissionContextByNameRequest)

PermissionContextAppService_permissionContextByNameResponse = _reflection.GeneratedProtocolMessageType('PermissionContextAppService_permissionContextByNameResponse', (_message.Message,), {
  'DESCRIPTOR' : _RESOURCETYPEAPPSERVICE_RESOURCETYPEBYNAMERESPONSE,
  '__module__' : 'permission_context_app_service_pb2'
  # @@protoc_insertion_point(class_scope:cafm.identity.permission_context.PermissionContextAppService_permissionContextByNameResponse)
  })
_sym_db.RegisterMessage(PermissionContextAppService_permissionContextByNameResponse)

PermissionContextAppService_permissionContextByIdRequest = _reflection.GeneratedProtocolMessageType('PermissionContextAppService_permissionContextByIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _RESOURCETYPEAPPSERVICE_RESOURCETYPEBYIDREQUEST,
  '__module__' : 'permission_context_app_service_pb2'
  # @@protoc_insertion_point(class_scope:cafm.identity.permission_context.PermissionContextAppService_permissionContextByIdRequest)
  })
_sym_db.RegisterMessage(PermissionContextAppService_permissionContextByIdRequest)

PermissionContextAppService_permissionContextByIdResponse = _reflection.GeneratedProtocolMessageType('PermissionContextAppService_permissionContextByIdResponse', (_message.Message,), {
  'DESCRIPTOR' : _RESOURCETYPEAPPSERVICE_RESOURCETYPEBYIDRESPONSE,
  '__module__' : 'permission_context_app_service_pb2'
  # @@protoc_insertion_point(class_scope:cafm.identity.permission_context.PermissionContextAppService_permissionContextByIdResponse)
  })
_sym_db.RegisterMessage(PermissionContextAppService_permissionContextByIdResponse)

PermissionContextAppService_permissionContextsRequest = _reflection.GeneratedProtocolMessageType('PermissionContextAppService_permissionContextsRequest', (_message.Message,), {
  'DESCRIPTOR' : _RESOURCETYPEAPPSERVICE_RESOURCETYPESREQUEST,
  '__module__' : 'permission_context_app_service_pb2'
  # @@protoc_insertion_point(class_scope:cafm.identity.permission_context.PermissionContextAppService_permissionContextsRequest)
  })
_sym_db.RegisterMessage(PermissionContextAppService_permissionContextsRequest)

PermissionContextAppService_permissionContextsResponse = _reflection.GeneratedProtocolMessageType('PermissionContextAppService_permissionContextsResponse', (_message.Message,), {
  'DESCRIPTOR' : _RESOURCETYPEAPPSERVICE_RESOURCETYPESRESPONSE,
  '__module__' : 'permission_context_app_service_pb2'
  # @@protoc_insertion_point(class_scope:cafm.identity.permission_context.PermissionContextAppService_permissionContextsResponse)
  })
_sym_db.RegisterMessage(PermissionContextAppService_permissionContextsResponse)



_RESOURCETYPEAPPSERVICE = _descriptor.ServiceDescriptor(
  name='PermissionContextAppService',
  full_name='cafm.identity.permission_context.PermissionContextAppService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=726,
  serialized_end=1281,
  methods=[
  _descriptor.MethodDescriptor(
    name='permissionContextByName',
    full_name='cafm.identity.permission_context.PermissionContextAppService.permissionContextByName',
    index=0,
    containing_service=None,
    input_type=_RESOURCETYPEAPPSERVICE_RESOURCETYPEBYNAMEREQUEST,
    output_type=_RESOURCETYPEAPPSERVICE_RESOURCETYPEBYNAMERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='permissionContextById',
    full_name='cafm.identity.permission_context.PermissionContextAppService.permissionContextById',
    index=1,
    containing_service=None,
    input_type=_RESOURCETYPEAPPSERVICE_RESOURCETYPEBYIDREQUEST,
    output_type=_RESOURCETYPEAPPSERVICE_RESOURCETYPEBYIDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='permissionContexts',
    full_name='cafm.identity.permission_context.PermissionContextAppService.permissionContexts',
    index=2,
    containing_service=None,
    input_type=_RESOURCETYPEAPPSERVICE_RESOURCETYPESREQUEST,
    output_type=_RESOURCETYPEAPPSERVICE_RESOURCETYPESRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RESOURCETYPEAPPSERVICE)

DESCRIPTOR.services_by_name['PermissionContextAppService'] = _RESOURCETYPEAPPSERVICE

# @@protoc_insertion_point(module_scope)
