# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import user_app_service_pb2 as user__app__service__pb2


class UserAppServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.userByNameAndPassword = channel.unary_unary(
                '/cafm.identity.user.UserAppService/userByNameAndPassword',
                request_serializer=user__app__service__pb2.UserAppService_userByNameAndPasswordRequest.SerializeToString,
                response_deserializer=user__app__service__pb2.UserAppService_userByNameAndPasswordResponse.FromString,
                )


class UserAppServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def userByNameAndPassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserAppServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'userByNameAndPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.userByNameAndPassword,
                    request_deserializer=user__app__service__pb2.UserAppService_userByNameAndPasswordRequest.FromString,
                    response_serializer=user__app__service__pb2.UserAppService_userByNameAndPasswordResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cafm.identity.user.UserAppService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UserAppService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def userByNameAndPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cafm.identity.user.UserAppService/userByNameAndPassword',
            user__app__service__pb2.UserAppService_userByNameAndPasswordRequest.SerializeToString,
            user__app__service__pb2.UserAppService_userByNameAndPasswordResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
