# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/authz_app_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='identity/authz_app_service.proto',
  package='cafm.identity.authz',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n identity/authz_app_service.proto\x12\x13\x63\x61\x66m.identity.authz\"r\n AuthzAppService_isAllowedRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x1a\n\x12permission_context\x18\x03 \x01(\t\x12\x13\n\x0bresource_id\x18\x04 \x01(\t\"6\n!AuthzAppService_isAllowedResponse\x12\x11\n\tisAllowed\x18\x01 \x01(\x08\x32\x8f\x01\n\x0f\x41uthzAppService\x12|\n\tisAllowed\x12\x35.cafm.identity.authz.AuthzAppService_isAllowedRequest\x1a\x36.cafm.identity.authz.AuthzAppService_isAllowedResponse\"\x00\x62\x06proto3'
)




_AUTHZAPPSERVICE_ISALLOWEDREQUEST = _descriptor.Descriptor(
  name='AuthzAppService_isAllowedRequest',
  full_name='cafm.identity.authz.AuthzAppService_isAllowedRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='cafm.identity.authz.AuthzAppService_isAllowedRequest.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='action', full_name='cafm.identity.authz.AuthzAppService_isAllowedRequest.action', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='permission_context', full_name='cafm.identity.authz.AuthzAppService_isAllowedRequest.permission_context', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resource_id', full_name='cafm.identity.authz.AuthzAppService_isAllowedRequest.resource_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=171,
)


_AUTHZAPPSERVICE_ISALLOWEDRESPONSE = _descriptor.Descriptor(
  name='AuthzAppService_isAllowedResponse',
  full_name='cafm.identity.authz.AuthzAppService_isAllowedResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='isAllowed', full_name='cafm.identity.authz.AuthzAppService_isAllowedResponse.isAllowed', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=227,
)

DESCRIPTOR.message_types_by_name['AuthzAppService_isAllowedRequest'] = _AUTHZAPPSERVICE_ISALLOWEDREQUEST
DESCRIPTOR.message_types_by_name['AuthzAppService_isAllowedResponse'] = _AUTHZAPPSERVICE_ISALLOWEDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AuthzAppService_isAllowedRequest = _reflection.GeneratedProtocolMessageType('AuthzAppService_isAllowedRequest', (_message.Message,), {
  'DESCRIPTOR' : _AUTHZAPPSERVICE_ISALLOWEDREQUEST,
  '__module__' : 'identity.authz_app_service_pb2'
  # @@protoc_insertion_point(class_scope:cafm.identity.authz.AuthzAppService_isAllowedRequest)
  })
_sym_db.RegisterMessage(AuthzAppService_isAllowedRequest)

AuthzAppService_isAllowedResponse = _reflection.GeneratedProtocolMessageType('AuthzAppService_isAllowedResponse', (_message.Message,), {
  'DESCRIPTOR' : _AUTHZAPPSERVICE_ISALLOWEDRESPONSE,
  '__module__' : 'identity.authz_app_service_pb2'
  # @@protoc_insertion_point(class_scope:cafm.identity.authz.AuthzAppService_isAllowedResponse)
  })
_sym_db.RegisterMessage(AuthzAppService_isAllowedResponse)



_AUTHZAPPSERVICE = _descriptor.ServiceDescriptor(
  name='AuthzAppService',
  full_name='cafm.identity.authz.AuthzAppService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=230,
  serialized_end=373,
  methods=[
  _descriptor.MethodDescriptor(
    name='isAllowed',
    full_name='cafm.identity.authz.AuthzAppService.isAllowed',
    index=0,
    containing_service=None,
    input_type=_AUTHZAPPSERVICE_ISALLOWEDREQUEST,
    output_type=_AUTHZAPPSERVICE_ISALLOWEDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_AUTHZAPPSERVICE)

DESCRIPTOR.services_by_name['AuthzAppService'] = _AUTHZAPPSERVICE

# @@protoc_insertion_point(module_scope)
