# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from identity import permission_context_app_service_pb2 as identity_dot_permission__context__app__service__pb2


class PermissionContextAppServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.permissionContextById = channel.unary_unary(
                '/cafm.identity.permission.PermissionContextAppService/permissionContextById',
                request_serializer=identity_dot_permission__context__app__service__pb2.PermissionContextAppService_permissionContextByIdRequest.SerializeToString,
                response_deserializer=identity_dot_permission__context__app__service__pb2.PermissionContextAppService_permissionContextByIdResponse.FromString,
                )
        self.permissionContexts = channel.unary_unary(
                '/cafm.identity.permission.PermissionContextAppService/permissionContexts',
                request_serializer=identity_dot_permission__context__app__service__pb2.PermissionContextAppService_permissionContextsRequest.SerializeToString,
                response_deserializer=identity_dot_permission__context__app__service__pb2.PermissionContextAppService_permissionContextsResponse.FromString,
                )


class PermissionContextAppServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def permissionContextById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def permissionContexts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PermissionContextAppServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'permissionContextById': grpc.unary_unary_rpc_method_handler(
                    servicer.permissionContextById,
                    request_deserializer=identity_dot_permission__context__app__service__pb2.PermissionContextAppService_permissionContextByIdRequest.FromString,
                    response_serializer=identity_dot_permission__context__app__service__pb2.PermissionContextAppService_permissionContextByIdResponse.SerializeToString,
            ),
            'permissionContexts': grpc.unary_unary_rpc_method_handler(
                    servicer.permissionContexts,
                    request_deserializer=identity_dot_permission__context__app__service__pb2.PermissionContextAppService_permissionContextsRequest.FromString,
                    response_serializer=identity_dot_permission__context__app__service__pb2.PermissionContextAppService_permissionContextsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cafm.identity.permission.PermissionContextAppService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PermissionContextAppService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def permissionContextById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cafm.identity.permission.PermissionContextAppService/permissionContextById',
            identity_dot_permission__context__app__service__pb2.PermissionContextAppService_permissionContextByIdRequest.SerializeToString,
            identity_dot_permission__context__app__service__pb2.PermissionContextAppService_permissionContextByIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def permissionContexts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cafm.identity.permission.PermissionContextAppService/permissionContexts',
            identity_dot_permission__context__app__service__pb2.PermissionContextAppService_permissionContextsRequest.SerializeToString,
            identity_dot_permission__context__app__service__pb2.PermissionContextAppService_permissionContextsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
