# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/permission_app_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from identity import permission_pb2 as identity_dot_permission__pb2
import order_pb2 as order__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='identity/permission_app_service.proto',
  package='cafm.identity.permission',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n%identity/permission_app_service.proto\x12\x18\x63\x61\x66m.identity.permission\x1a\x19identity/permission.proto\x1a\x0border.proto\"<\n,PermissionAppService_permissionByNameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"i\n-PermissionAppService_permissionByNameResponse\x12\x38\n\npermission\x18\x01 \x01(\x0b\x32$.cafm.identity.permission.Permission\"8\n*PermissionAppService_permissionByIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"g\n+PermissionAppService_permissionByIdResponse\x12\x38\n\npermission\x18\x01 \x01(\x0b\x32$.cafm.identity.permission.Permission\"z\n\'PermissionAppService_permissionsRequest\x12\x12\n\nresultFrom\x18\x01 \x01(\x05\x12\x12\n\nresultSize\x18\x02 \x01(\x05\x12\'\n\x05order\x18\x03 \x03(\x0b\x32\x18.cafm.common.order.Order\"x\n(PermissionAppService_permissionsResponse\x12\x39\n\x0bpermissions\x18\x01 \x03(\x0b\x32$.cafm.identity.permission.Permission\x12\x11\n\titemCount\x18\x02 \x01(\x05\x32\xf9\x03\n\x14PermissionAppService\x12\xa5\x01\n\x10permissionByName\x12\x46.cafm.identity.permission.PermissionAppService_permissionByNameRequest\x1aG.cafm.identity.permission.PermissionAppService_permissionByNameResponse\"\x00\x12\x9f\x01\n\x0epermissionById\x12\x44.cafm.identity.permission.PermissionAppService_permissionByIdRequest\x1a\x45.cafm.identity.permission.PermissionAppService_permissionByIdResponse\"\x00\x12\x96\x01\n\x0bpermissions\x12\x41.cafm.identity.permission.PermissionAppService_permissionsRequest\x1a\x42.cafm.identity.permission.PermissionAppService_permissionsResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[identity_dot_permission__pb2.DESCRIPTOR,order__pb2.DESCRIPTOR,])




_PERMISSIONAPPSERVICE_PERMISSIONBYNAMEREQUEST = _descriptor.Descriptor(
  name='PermissionAppService_permissionByNameRequest',
  full_name='cafm.identity.permission.PermissionAppService_permissionByNameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='cafm.identity.permission.PermissionAppService_permissionByNameRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=167,
)


_PERMISSIONAPPSERVICE_PERMISSIONBYNAMERESPONSE = _descriptor.Descriptor(
  name='PermissionAppService_permissionByNameResponse',
  full_name='cafm.identity.permission.PermissionAppService_permissionByNameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='permission', full_name='cafm.identity.permission.PermissionAppService_permissionByNameResponse.permission', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=274,
)


_PERMISSIONAPPSERVICE_PERMISSIONBYIDREQUEST = _descriptor.Descriptor(
  name='PermissionAppService_permissionByIdRequest',
  full_name='cafm.identity.permission.PermissionAppService_permissionByIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='cafm.identity.permission.PermissionAppService_permissionByIdRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=332,
)


_PERMISSIONAPPSERVICE_PERMISSIONBYIDRESPONSE = _descriptor.Descriptor(
  name='PermissionAppService_permissionByIdResponse',
  full_name='cafm.identity.permission.PermissionAppService_permissionByIdResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='permission', full_name='cafm.identity.permission.PermissionAppService_permissionByIdResponse.permission', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=334,
  serialized_end=437,
)


_PERMISSIONAPPSERVICE_PERMISSIONSREQUEST = _descriptor.Descriptor(
  name='PermissionAppService_permissionsRequest',
  full_name='cafm.identity.permission.PermissionAppService_permissionsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='resultFrom', full_name='cafm.identity.permission.PermissionAppService_permissionsRequest.resultFrom', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resultSize', full_name='cafm.identity.permission.PermissionAppService_permissionsRequest.resultSize', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='order', full_name='cafm.identity.permission.PermissionAppService_permissionsRequest.order', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=439,
  serialized_end=561,
)


_PERMISSIONAPPSERVICE_PERMISSIONSRESPONSE = _descriptor.Descriptor(
  name='PermissionAppService_permissionsResponse',
  full_name='cafm.identity.permission.PermissionAppService_permissionsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='permissions', full_name='cafm.identity.permission.PermissionAppService_permissionsResponse.permissions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='itemCount', full_name='cafm.identity.permission.PermissionAppService_permissionsResponse.itemCount', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=563,
  serialized_end=683,
)

_PERMISSIONAPPSERVICE_PERMISSIONBYNAMERESPONSE.fields_by_name['permission'].message_type = identity_dot_permission__pb2._PERMISSION
_PERMISSIONAPPSERVICE_PERMISSIONBYIDRESPONSE.fields_by_name['permission'].message_type = identity_dot_permission__pb2._PERMISSION
_PERMISSIONAPPSERVICE_PERMISSIONSREQUEST.fields_by_name['order'].message_type = order__pb2._ORDER
_PERMISSIONAPPSERVICE_PERMISSIONSRESPONSE.fields_by_name['permissions'].message_type = identity_dot_permission__pb2._PERMISSION
DESCRIPTOR.message_types_by_name['PermissionAppService_permissionByNameRequest'] = _PERMISSIONAPPSERVICE_PERMISSIONBYNAMEREQUEST
DESCRIPTOR.message_types_by_name['PermissionAppService_permissionByNameResponse'] = _PERMISSIONAPPSERVICE_PERMISSIONBYNAMERESPONSE
DESCRIPTOR.message_types_by_name['PermissionAppService_permissionByIdRequest'] = _PERMISSIONAPPSERVICE_PERMISSIONBYIDREQUEST
DESCRIPTOR.message_types_by_name['PermissionAppService_permissionByIdResponse'] = _PERMISSIONAPPSERVICE_PERMISSIONBYIDRESPONSE
DESCRIPTOR.message_types_by_name['PermissionAppService_permissionsRequest'] = _PERMISSIONAPPSERVICE_PERMISSIONSREQUEST
DESCRIPTOR.message_types_by_name['PermissionAppService_permissionsResponse'] = _PERMISSIONAPPSERVICE_PERMISSIONSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PermissionAppService_permissionByNameRequest = _reflection.GeneratedProtocolMessageType('PermissionAppService_permissionByNameRequest', (_message.Message,), {
  'DESCRIPTOR' : _PERMISSIONAPPSERVICE_PERMISSIONBYNAMEREQUEST,
  '__module__' : 'identity.permission_app_service_pb2'
  # @@protoc_insertion_point(class_scope:cafm.identity.permission.PermissionAppService_permissionByNameRequest)
  })
_sym_db.RegisterMessage(PermissionAppService_permissionByNameRequest)

PermissionAppService_permissionByNameResponse = _reflection.GeneratedProtocolMessageType('PermissionAppService_permissionByNameResponse', (_message.Message,), {
  'DESCRIPTOR' : _PERMISSIONAPPSERVICE_PERMISSIONBYNAMERESPONSE,
  '__module__' : 'identity.permission_app_service_pb2'
  # @@protoc_insertion_point(class_scope:cafm.identity.permission.PermissionAppService_permissionByNameResponse)
  })
_sym_db.RegisterMessage(PermissionAppService_permissionByNameResponse)

PermissionAppService_permissionByIdRequest = _reflection.GeneratedProtocolMessageType('PermissionAppService_permissionByIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _PERMISSIONAPPSERVICE_PERMISSIONBYIDREQUEST,
  '__module__' : 'identity.permission_app_service_pb2'
  # @@protoc_insertion_point(class_scope:cafm.identity.permission.PermissionAppService_permissionByIdRequest)
  })
_sym_db.RegisterMessage(PermissionAppService_permissionByIdRequest)

PermissionAppService_permissionByIdResponse = _reflection.GeneratedProtocolMessageType('PermissionAppService_permissionByIdResponse', (_message.Message,), {
  'DESCRIPTOR' : _PERMISSIONAPPSERVICE_PERMISSIONBYIDRESPONSE,
  '__module__' : 'identity.permission_app_service_pb2'
  # @@protoc_insertion_point(class_scope:cafm.identity.permission.PermissionAppService_permissionByIdResponse)
  })
_sym_db.RegisterMessage(PermissionAppService_permissionByIdResponse)

PermissionAppService_permissionsRequest = _reflection.GeneratedProtocolMessageType('PermissionAppService_permissionsRequest', (_message.Message,), {
  'DESCRIPTOR' : _PERMISSIONAPPSERVICE_PERMISSIONSREQUEST,
  '__module__' : 'identity.permission_app_service_pb2'
  # @@protoc_insertion_point(class_scope:cafm.identity.permission.PermissionAppService_permissionsRequest)
  })
_sym_db.RegisterMessage(PermissionAppService_permissionsRequest)

PermissionAppService_permissionsResponse = _reflection.GeneratedProtocolMessageType('PermissionAppService_permissionsResponse', (_message.Message,), {
  'DESCRIPTOR' : _PERMISSIONAPPSERVICE_PERMISSIONSRESPONSE,
  '__module__' : 'identity.permission_app_service_pb2'
  # @@protoc_insertion_point(class_scope:cafm.identity.permission.PermissionAppService_permissionsResponse)
  })
_sym_db.RegisterMessage(PermissionAppService_permissionsResponse)



_PERMISSIONAPPSERVICE = _descriptor.ServiceDescriptor(
  name='PermissionAppService',
  full_name='cafm.identity.permission.PermissionAppService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=686,
  serialized_end=1191,
  methods=[
  _descriptor.MethodDescriptor(
    name='permissionByName',
    full_name='cafm.identity.permission.PermissionAppService.permissionByName',
    index=0,
    containing_service=None,
    input_type=_PERMISSIONAPPSERVICE_PERMISSIONBYNAMEREQUEST,
    output_type=_PERMISSIONAPPSERVICE_PERMISSIONBYNAMERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='permissionById',
    full_name='cafm.identity.permission.PermissionAppService.permissionById',
    index=1,
    containing_service=None,
    input_type=_PERMISSIONAPPSERVICE_PERMISSIONBYIDREQUEST,
    output_type=_PERMISSIONAPPSERVICE_PERMISSIONBYIDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='permissions',
    full_name='cafm.identity.permission.PermissionAppService.permissions',
    index=2,
    containing_service=None,
    input_type=_PERMISSIONAPPSERVICE_PERMISSIONSREQUEST,
    output_type=_PERMISSIONAPPSERVICE_PERMISSIONSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PERMISSIONAPPSERVICE)

DESCRIPTOR.services_by_name['PermissionAppService'] = _PERMISSIONAPPSERVICE

# @@protoc_insertion_point(module_scope)
