# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/policy_app_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from identity import user_with_role_pb2 as identity_dot_user__with__role__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='identity/policy_app_service.proto',
  package='cafm.identity.policy',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n!identity/policy_app_service.proto\x12\x14\x63\x61\x66m.identity.policy\x1a\x1didentity/user_with_role.proto\".\n,PolicyAppService_usersWithAccessRolesRequest\"\x8b\x01\n-PolicyAppService_usersWithAccessRolesResponse\x12@\n\x14user_with_role_items\x18\x01 \x03(\x0b\x32\".cafm.identity.policy.UserWithRole\x12\x18\n\x10total_item_count\x18\x02 \x01(\x05\x32\xb9\x01\n\x10PolicyAppService\x12\xa4\x01\n\x17users_with_access_roles\x12\x42.cafm.identity.policy.PolicyAppService_usersWithAccessRolesRequest\x1a\x43.cafm.identity.policy.PolicyAppService_usersWithAccessRolesResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[identity_dot_user__with__role__pb2.DESCRIPTOR,])




_POLICYAPPSERVICE_USERSWITHACCESSROLESREQUEST = _descriptor.Descriptor(
  name='PolicyAppService_usersWithAccessRolesRequest',
  full_name='cafm.identity.policy.PolicyAppService_usersWithAccessRolesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=136,
)


_POLICYAPPSERVICE_USERSWITHACCESSROLESRESPONSE = _descriptor.Descriptor(
  name='PolicyAppService_usersWithAccessRolesResponse',
  full_name='cafm.identity.policy.PolicyAppService_usersWithAccessRolesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_with_role_items', full_name='cafm.identity.policy.PolicyAppService_usersWithAccessRolesResponse.user_with_role_items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_item_count', full_name='cafm.identity.policy.PolicyAppService_usersWithAccessRolesResponse.total_item_count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=278,
)

_POLICYAPPSERVICE_USERSWITHACCESSROLESRESPONSE.fields_by_name['user_with_role_items'].message_type = identity_dot_user__with__role__pb2._USERWITHROLE
DESCRIPTOR.message_types_by_name['PolicyAppService_usersWithAccessRolesRequest'] = _POLICYAPPSERVICE_USERSWITHACCESSROLESREQUEST
DESCRIPTOR.message_types_by_name['PolicyAppService_usersWithAccessRolesResponse'] = _POLICYAPPSERVICE_USERSWITHACCESSROLESRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PolicyAppService_usersWithAccessRolesRequest = _reflection.GeneratedProtocolMessageType('PolicyAppService_usersWithAccessRolesRequest', (_message.Message,), {
  'DESCRIPTOR' : _POLICYAPPSERVICE_USERSWITHACCESSROLESREQUEST,
  '__module__' : 'identity.policy_app_service_pb2'
  # @@protoc_insertion_point(class_scope:cafm.identity.policy.PolicyAppService_usersWithAccessRolesRequest)
  })
_sym_db.RegisterMessage(PolicyAppService_usersWithAccessRolesRequest)

PolicyAppService_usersWithAccessRolesResponse = _reflection.GeneratedProtocolMessageType('PolicyAppService_usersWithAccessRolesResponse', (_message.Message,), {
  'DESCRIPTOR' : _POLICYAPPSERVICE_USERSWITHACCESSROLESRESPONSE,
  '__module__' : 'identity.policy_app_service_pb2'
  # @@protoc_insertion_point(class_scope:cafm.identity.policy.PolicyAppService_usersWithAccessRolesResponse)
  })
_sym_db.RegisterMessage(PolicyAppService_usersWithAccessRolesResponse)



_POLICYAPPSERVICE = _descriptor.ServiceDescriptor(
  name='PolicyAppService',
  full_name='cafm.identity.policy.PolicyAppService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=281,
  serialized_end=466,
  methods=[
  _descriptor.MethodDescriptor(
    name='users_with_access_roles',
    full_name='cafm.identity.policy.PolicyAppService.users_with_access_roles',
    index=0,
    containing_service=None,
    input_type=_POLICYAPPSERVICE_USERSWITHACCESSROLESREQUEST,
    output_type=_POLICYAPPSERVICE_USERSWITHACCESSROLESRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_POLICYAPPSERVICE)

DESCRIPTOR.services_by_name['PolicyAppService'] = _POLICYAPPSERVICE

# @@protoc_insertion_point(module_scope)
